version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  allow:
    # For now, only enable the deps we know we want to keep fresh
    - dependency-name: "github.com/coreos/butane"
    - dependency-name: "github.com/coreos/ignition/v2"
    - dependency-name: "github.com/coreos/stream-metadata-go"
