#!/bin/bash -e

cd $(dirname $0)

source ./env

if [[ $# -eq 0 ]]; then
	set -- cmd/*
fi

version=$(git describe --dirty)
version="${version#v}"
version="${version/-/+}"
ldflags="-X ${REPO_PATH}/version.Version=${version}"

for cmd in "$@"; do
	cmd=$(basename "${cmd}")
	echo "Building ${cmd}..."
	go build -i -ldflags "${ldflags}" \
            -o "bin/${cmd}" "${REPO_PATH}/cmd/${cmd}"
done

