#!/bin/bash -e

PROJ="mantle"
ORG_PATH="github.com/coreos"
REPO_PATH="${ORG_PATH}/${PROJ}"

if [ ! -h gopath/src/${REPO_PATH} ]; then
	mkdir -p gopath/src/${ORG_PATH}
	ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath

eval $(go env)

echo "Building kola..."
go build -o bin/kola ${REPO_PATH}/cmd/kola
go build -o bin/kolet ${REPO_PATH}/cmd/kolet
echo "Building plume..."
go build -o bin/plume ${REPO_PATH}/cmd/plume
echo "Building ore..."
go build -o bin/ore ${REPO_PATH}/cmd/ore
