#!/usr/bin/env bash
set -euo pipefail
# Usage: coreos-assembler <cmd> ...
# Currently this just wraps the two binaries we have today
# under a global entrypoint with subcommands.

# docker/podman don't run through PAM, but we want this set
export USER=${USER:-$(id -nu)}

# Ensure we've unshared our mount namespace so
# the later umount doesn't affect the host potentially
if [ -e /sys/fs/selinux/status ]; then
    if [ -z "${coreos_assembler_unshared:-}" ]; then
        exec sudo -- env coreos_assembler_unshared=1 unshare -m -- runuser -u ${USER} -- $0 "$@"
    else
        # Work around https://github.com/containers/libpod/issues/1448
        sudo umount /sys/fs/selinux
    fi
fi

cmd=${1:-}
build_commands="init fetch build run prune clean"
other_commands="shell"
utility_commands="gf-oemid virt-install oscontainer"
if [ -z "${cmd}" ]; then
    echo usage: "coreos-assembler CMD ..."
    echo "Build commands:"
    for bin in ${build_commands}; do
        echo "  ${bin}"
    done

    echo "Other commands:"
    for bin in ${other_commands}; do
        echo "  ${bin}"
    done

    echo "Utility commands:"
    for bin in ${utility_commands}; do
        echo "  ${bin}"
    done
    exit 1
fi
shift

target=/usr/lib/coreos-assembler/cmd-${cmd}
if test -x "${target}"; then
    exec ${target} "$@"
fi

echo "Unknown command: ${cmd}" 1>&2
exit 1
