#!/usr/bin/env bash
set -euo pipefail
# Usage: coreos-assembler <cmd> ...
# Currently this just wraps the two binaries we have today
# under a global entrypoint with subcommands.

# docker/podman don't run through PAM, but we want this set
export USER=${USER:-$(id -nu)}

# Ensure we've unshared our mount namespace so
# the later umount doesn't affect the host potentially
if [ -z "${coreos_assembler_unshared:-}" ]; then
    exec sudo -- env coreos_assembler_unshared=1 unshare -m -- runuser -u ${USER} -- $0 "$@"
fi
# Work around https://github.com/containers/libpod/issues/1448
if [ -e /sys/fs/selinux/status ]; then
    sudo umount /sys/fs/selinux
fi

cmd=${1:-}
if [ -z "${cmd}" ]; then
    echo usage: "coreos-assembler CMD ..."
    echo "Commands:"
    ls /usr/libexec/coreos-assembler/cmd-* | while read cmd; do
        bin=$(basename $cmd)
        echo "  ${bin:4}"
    done
    exit 1
fi
shift

target=/usr/libexec/coreos-assembler/cmd-${cmd}
if test -x "${target}"; then
    exec ${target} "$@"
fi

echo "Unknown command: ${cmd}" 1>&2
exit 1
