#!/usr/bin/env bash
set -euo pipefail
# Usage: coreos-assembler <cmd> ...
# Currently this just wraps the two binaries we have today
# under a global entrypoint with subcommands.

export USER=${USER:-$(id -nu)}

case $USER in
    root) exec runuser -u builder -- $0 "$@";;
    builder) ;;
    *) echo "Executed as non-builder user; assuming sudo rights..." 1>&2;;
esac

cmd=${1:-}
shift

if [ -z "${cmd}" ]; then
    echo usage: "coreos-assembler CMD ..."
    echo "Commands:"
    ls /usr/libexec/coreos-assembler/cmd-* | while read cmd; do
        bin=$(basename $cmd)
        echo "  ${bin:4}"
    done
    exit 1
fi

target=/usr/libexec/coreos-assembler/cmd-${cmd}
if test -x "${target}"; then
    exec ${target} "$@"
fi

echo "Unknown command: ${cmd}" 1>&2
exit 1
