# Instead of doing a slow, whole-cloth build for developer
# tests, you can quickly test changes via this file. This
# especially useful for changes to dependencies or for final
# verification of COSA code.
#
# This moves the build time from ~15 minutes to ~3-5 minutes.
# Example: buildah bud -f Dockerfile.dev -t localhost/cosa-test .

FROM quay.io/coreos-assembler/coreos-assembler:latest
WORKDIR /root/containerbuild

USER root
RUN rm -rfv /lib/coreos-assembler /usr/bin/coreos-assembler

COPY ./src/print-dependencies.sh ./src/deps*.txt ./src/vmdeps*.txt ./src/build-deps.txt /root/containerbuild/src/
COPY ./build.sh /root/containerbuild/
RUN ./build.sh install_rpms
RUN echo Dockerfile.dev > /usr/lib/coreos-assembler/.built-via-container

COPY ./ /root/containerbuild/
RUN ./build.sh write_archive_info
RUN ./build.sh make_and_makeinstall

RUN make clean

WORKDIR /srv/

# run as `builder` user
USER builder
ENTRYPOINT ["/usr/bin/dumb-init", "/usr/bin/coreos-assembler"]
