#!/bin/bash -e
#
# Run all tests
#   ./test
#   ./test -v
#
# Run tests for one package
#   PKG=./foo ./test
#

# A replacement for `go fmt` that calls gofmt without -w
gofmt-l() {
    set -- $(go list "$@")
    pushd "${GOPATH}/src" >/dev/null
    c=$(gofmt -l "$@" | tee /dev/stderr | wc -c)
    popd >/dev/null
    if [[ $c -ne 0 ]]; then
        echo "gofmt check failed" >&2
        return 1
    fi
}

source ./env
# Use an alternate bin to avoid clobbering output from ./build
export GOBIN="${GOPATH}/_testbin"
# cd via the symlink so ./... and so on resolves correctly.
cd gopath/src/${REPO_PATH}

# PKG may be passed in from ./cover
[[ -z "$PKG" ]] && PKG="./..."

echo "Building tests..."
go test -i "$@" $PKG
go install $PKG

echo "Running tests..."
go test -cover "$@" $PKG

echo "Checking gofmt..."
gofmt-l $PKG

echo "Checking govet..."
go vet $PKG

echo "Success"
