apiVersion: v1
kind: Template
labels:
  app: cosa
  template: cosa-template
metadata:
  annotations:
    description: CoreOS Assembler Images
    openshift.io/display-name: CoreOS Assembler
    tags: cosa,coreos-assembler
  name: cosa-images

parameters:
  - description: Git source URI
    name: REPO_URL
    value: https://github.com/coreos/fedora-coreos-config
  - description: Git branch/tag reference
    name: REPO_REF
    value: testing-devel
  - description: Name of the image; use e.g. joe-cosa for your own build
    name: IMAGE
    value: coreos-assembler
  - description: Image Tag to use
    name: IMAGE_TAG
    value: buildconfig-main
  - description: Service Account
    name: SA
    value: cosa-builder
  - description: Tag to use for this template
    name: TAG
    value: main

objects:

# Create the Service Account for COSA
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      coreos-assembler.coreos.com/type: "service account"
    name: ${SA}
  name: ${SA}

# Gangplank uses similar permissions to Jenkins
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: coreos-builder-editor-0
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${SA}

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: machine-os-content
  spec:
    lookupPolicy:
      local: true

# Create the basic build config
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: cosa-runner
      template: cosa-runner-template
    name: cosa-runner-${TAG}
  spec:
    failedBuildsHistoryLimit: 25
    successfulBuildsHistoryLimit: 25
    nodeSelector: null
    output:
    to:
      kind: ImageStreamTag
      name: machine-os-content:latest
    postCommit: {}
    resources: {}
    runPolicy: Parallel
    serviceAccount: ${SA}
    source:
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      customStrategy:
        env:
        - name: COSA_CMDS
          value: 'cosa fetch; cosa build;'
        from:
          kind: ImageStreamTag
          name: ${IMAGE}:${IMAGE_TAG}
        forcePull: true
      type: Custom
    triggers: []
