FROM quay.io/coreos-assembler/coreos-assembler:latest
WORKDIR /root/containerbuild

USER root

COPY ./ /root/containerbuild/
RUN cd /root/containerbuild/gangplank && \
    make && \
    make install DESTDIR=/ && \
    install -v -D -t /usr/lib/coreos-assembler /root/containerbuild/src/*.{sh,txt}

WORKDIR /srv/

USER builder
ENTRYPOINT ["/usr/bin/dumb-init", "/usr/bin/gangway"]
