#!/usr/bin/env python3

import csv
import hashlib
import requests
import sys
import yaml

"""
This script converts a CSV file containing artifact definitions into a YAML
lock file.

For each row in the input CSV, it expects the following columns:
- 'download_url': The URL from which to download the artifact.
- 'checksum': The name of the hash algorithm (e.g., 'sha256', 'sha512')
- 'filename': The name of the output file.

The script performs the following actions:
1. Reads the input CSV file row by row.
2. For each artifact, it downloads the content from the 'download_url'.
3. It calculates the checksum of the downloaded content using the specified
   hash algorithm.
4. It updates the 'checksum' field in the row to include both the algorithm
   and the calculated checksum in the format '<algorithm>:<checksum>'.
5. Writes the transformed data, along with a metadata header, into a YAML file.

The generated YAML file serves as a lock file, ensuring that artifacts can
be validated against their recorded checksums.

Usage:
    ./generate_artifacts_lock_file.py <input_csv_fpath> <output_yaml_fpath>

Example:
    ./generate_artifacts_lock_file.py artifacts.in.csv artifacts.lock.yaml
"""


def csv_to_yaml(csv_filepath: str, yaml_filepath: str) -> None:
    """
    Converts a CSV file to a YAML file.

    Each row in the CSV becomes an item in a YAML list.
    The CSV column names become keys in the dictionary for each item.

    Args:
        csv_filepath (str): The path to the input CSV file.
        yaml_filepath (str): The path to the output YAML file.
    """
    data = {'metadata': {'version': '1.0'}, 'artifacts': []}
    try:
        with open(csv_filepath, mode='r', newline='',
                  encoding='utf-8') as csv_file:
            csv_reader = csv.DictReader(csv_file)
            if csv_reader.fieldnames is None:
                print(f"Error: CSV file '{csv_filepath}' "
                      "is empty or has no header.", file=sys.stderr)
                return

            for row in csv_reader:
                # We calculate the checksum of the file using the hash
                # algorithm, and store the value in the desired format
                # '<hash_algorithm>:<checksum>'.
                row['checksum'] = "{}:{}".format(
                    row['checksum'],
                    calculate_checksum(row['download_url'], row['checksum'])
                )
                data['artifacts'].append(row)

        with open(yaml_filepath, mode='w', encoding='utf-8') as yaml_file:
            yaml_file.write(
                "# This file was generated automatically by '{}' "
                "from the content\n"
                "# of artifacts.in.csv. Do not edit this file, "
                "edit artifacts.in.csv instead."
                "\n#\n#           ANY CHANGES MADE HERE WILL BE LOST!\n#\n"
                "# In order to validate locally the data, please refer to "
                "the README file located at the root directory of this "
                "script.\n".format(sys.argv[0])
            )
            # Dump the list of dictionaries to YAML format
            yaml.dump(data, yaml_file, default_flow_style=False,
                      sort_keys=False, explicit_start=True)

        print(f"Successfully converted '{csv_filepath}' to '{yaml_filepath}'")

    except FileNotFoundError:
        print(f"Error: The file '{csv_filepath}' was not found.",
              file=sys.stderr)
    except Exception as e:
        print(f"An unexpected error occurred: {e}", file=sys.stderr)


def calculate_checksum(file_url: str, hash_algorithm: str) -> str | None:
    """
    Calculates the checksum of a file downloaded from a URL using a specified
    hash algorithm.

    Args:
        file_url (str): The URL of the file to download.
        hash_algorithm (str): The name of the hash algorithm to use
                              (e.g. 'sha256', 'sha512').

    Returns:
        str: The hexadecimal checksum of the downloaded file, or None if an
             error occurs.
    """
    try:
        hasher = hashlib.new(hash_algorithm)
    except ValueError:
        print(f"Error: Invalid hash algorithm '{hash_algorithm}'. "
              f"Available algorithms: {hashlib.algorithms_available}",
              file=sys.stderr)
        return None
    except Exception as e:
        print(f"An unexpected error occurred while initializing hash: {e}",
              file=sys.stderr)
        return None

    try:
        # Stream the download to handle large files without loading everything
        # into memory
        print(f"Pulling '{file_url}' and getting the checksum")
        with requests.get(file_url, stream=True) as r:
            # Raise an HTTPError for bad responses (4xx or 5xx)
            r.raise_for_status()
            for chunk in r.iter_content(chunk_size=4096):
                hasher.update(chunk)
        return hasher.hexdigest()
    except requests.exceptions.RequestException as e:
        print(f"Error downloading file from '{file_url}': {e}",
              file=sys.stderr)
        return None
    except Exception as e:
        print(f"An error occurred while processing the downloaded file: {e}",
              file=sys.stderr)
        return None


if __name__ == "__main__":
    # Example usage:
    #    ./generate_artifacts_lock_file.py artifacts.in.csv artifacts.lock.yaml

    if len(sys.argv) != 3:
        print("Usage: ./generate_artifacts_lock_file.py artifacts.in.csv "
              "artifacts.lock.yaml", file=sys.stderr)
        sys.exit(1)

    input_csv = sys.argv[1]
    output_yaml = sys.argv[2]

    csv_to_yaml(input_csv, output_yaml)
