#!/usr/bin/env bash

set -e

cd $(dirname $0)

source ./env

if [[ $# -eq 0 ]]; then
	set -- cmd/*
fi

version=$(git describe --tags --always --dirty)
version="${version#v}"
version="${version/-/+}"
ldflags="-X ${REPO_PATH}/version.Version=${version}"

host_build() {
	echo "Building $1"
	go build -i \
		-ldflags "${ldflags}" \
		-mod vendor \
		-o "bin/$1" \
		"${REPO_PATH}/cmd/$1"
}

# Unused now, but kept in case we want it in the future
cross_build() {
	local a
	for a in amd64 arm64 s390x ppc64le; do
		echo "Building $a/$1"
		mkdir -p "bin/$a"
		CGO_ENABLED=0 GOARCH=$a \
			go build -mod=vendor -ldflags "${ldflags}" \
			-o "bin/$a/$1" "${REPO_PATH}/cmd/$1"
	done
}

for cmd in "$@"; do
	cmd=$(basename "${cmd}")
	host_build "${cmd}"
done
