#!/usr/bin/env bash
set -eu

# This script uses schematyper, which must be installed and in the PATH.
#
# The purpose of this script is to generate cosa/cosa_<ver>.go. Whenever
# the schema is updated, this script should be run.

hash schematyper 2>/dev/null || {
    echo >&2 "schematyper must be installed and in the PATH to use this script: https://github.com/idubinskiy/schematyper"
    exit 1
}

schema_version="v1"
echo "Generating COSA Schema ${schema_version}"

schematyper "../src/schema/${schema_version}.json" \
    -o "cosa/cosa_${schema_version}.go" \
    --package="cosa" \
    --root-type=Build
