#!/bin/bash -xe
mydir=$(dirname $(readlink -f $0))
tdir="${mydir}/tmp"
mkdir -p "${tdir}"
trap "rm -rfv ${tdir}" EXIT

schema_version="v1"
schema_json="${schema_version}.json"
echo "Generating COSA Schema ${schema_version}"

out="${tdir}/cosa_${schema_version}.go"

"schematyper" \
    "${schema_version}.json" \
    -o "${out}" \
    --package="cosa" \
    --root-type=Build \
    --ptr-for-omit

# Avoid having a filename in generated code since it
# can vary depending on local checkout paths.
sed -e "s|^// generated.*|// generated by 'make schema'|g"  -i ${tdir}/cosa_v1.go

cat > "${tdir}/schema_doc.go" <<EOM
// Generated by ${0}
// DO NOT EDIT

package cosa

var generatedSchemaJSON = \`$(< ${schema_json})
\`
EOM

cp -av ${tdir}/*go ${mydir}/cosa/
