#!/bin/bash
set -euo pipefail
dn=$(cd $(dirname $0) && pwd)
toplevel=$(cd ${dn} && git rev-parse --show-toplevel)
set -x
cosa kola run --output-dir tmp/kolaself -E ${toplevel}/tests/kola-ci-self 'ext.kola-ci-self*' "$@"
log=$(find tmp/kolaself -type f -name kola-runext-autopkgtest-reboot.txt)
test -n "${log}"
if ! grep -qF -e 'ok autopkgtest rebooting' < "${log}"; then
  echo "failed to validate autopkgtest rebooting test output"
  exit 1
fi
