apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/coreos/coreos-assembler?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && target_branch.startsWith("renovate/") &&
      ("tests/containers/tang/***".pathChanged() ||
       "rpms.lock.yaml".pathChanged() ||
       "ci/hermetic/artifacts.lock.yaml".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: coreos-assembler-main
    appstudio.openshift.io/component: kola-tang-main
    pipelines.appstudio.openshift.io/type: build
    release.appstudio.openshift.io/auto-release: "false"
  name: kola-tang-main-renovate-on-push
  namespace: coreos-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/coreos-tenant/kola-tang-main:{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: ./tests/containers/tang/Containerfile
  - name: path-context
    value: .
  - name: skip-checks
    value: true
  - name: hermetic
    value: false
  #- name: prefetch-input
  #  value: '[{"type": "rpm", "path": "ci/hermetic"}]'
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-multi-platform-oci-ta@sha256:39a1abd4657035029db5e1e215333aba0cf094c3984df58e12cb157f4cb62207
    - name: name
      value: docker-build-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-kola-tang-main
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
