apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/coreos/coreos-assembler?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && target_branch.startsWith("renovate/") &&
      ("tests/containers/nfs/***".pathChanged() ||
       "rpms.lock.yaml".pathChanged() ||
       "ci/hermetic/artifacts.lock.yaml".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: coreos-assembler-main
    appstudio.openshift.io/component: kola-nfs-main
    pipelines.appstudio.openshift.io/type: build
    release.appstudio.openshift.io/auto-release: "false"
  name: kola-nfs-main-renovate-on-push
  namespace: coreos-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/coreos-tenant/kola-nfs-main:{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: tests/containers/nfs
  - name: skip-checks
    value: true
  - name: hermetic
    value: false
  #- name: prefetch-input
  #  value: '[{"type": "rpm", "path": "ci/hermetic"}]'
  # Note: to be removed once rpm fully supported
  # https://github.com/hermetoproject/hermeto?tab=readme-ov-file#package-managers
  - name: dev-package-managers
    value: true
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/jcapitao/tekton-catalog/pipeline-docker-build-multi-platform-oci-ta@sha256:a3993688715cba973af5e7fba95bc91f92673e8491f2524853736161974334fb
    - name: name
      value: docker-build-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-kola-nfs-main
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
