# This file defines the oci-archive and deployed-tree pipelines.
version: '2'
pipelines:
  # If installing from container then let's pull the container file into a pipeline
  - name: oci-archive
    stages:
      - mpp-if: ociarchive != ''
        then:
          type: org.osbuild.copy
          inputs:
            inlinefile:
              type: org.osbuild.files
              origin: org.osbuild.source
              mpp-embed:
                id: coreos.ociarchive
                url:
                  mpp-format-string: 'file://{ociarchive}'
          options:
            paths:
              - from:
                  mpp-format-string: input://inlinefile/{embedded['coreos.ociarchive']}
                to: tree:///coreos.ociarchive
        else:
          type: org.osbuild.noop
  # Construct a tree here that is a representation of the filesystem
  # that you would see on a running OSTree system. i.e. instead of just
  # /ostree and /sysroot at the toplevel we see /usr/ /var/ /etc/ ... that
  # you would see inside an OSTree deployment. Having the plain files accessible
  # allows for this pipeline to be used as a buildroot for some stages
  # or as inputs for others (i.e. file_context input to the org.osbuild.selinux
  # stages). This pipeline isn't actually used for built artifacts but
  # to help during build.
  #
  # NOTE: this is only used as a buildroot on RHCOS (FCOS doesn't ship python).
  - name: deployed-tree
    stages:
      - mpp-if: ociarchive != ''
        then:
          type: org.osbuild.container-deploy
          inputs:
            images:
              type: org.osbuild.containers
              origin: org.osbuild.pipeline
              references:
                name:oci-archive:
                  name: coreos.ociarchive
        else:
          type: org.osbuild.container-deploy
          inputs:
            images:
              type: org.osbuild.containers-storage
              origin: org.osbuild.source
              mpp-resolve-images:
                images:
                  - source: $container_repo
                    tag: $container_tag
