# This file defines the oci-archive, deployed-tree, and tree pipelines.
version: '2'
pipelines:
  # If installing from container then let's pull the container file into a pipeline
  - name: oci-archive
    stages:
      - mpp-if: ociarchive != ''
        then:
          type: org.osbuild.copy
          inputs:
            inlinefile:
              type: org.osbuild.files
              origin: org.osbuild.source
              mpp-embed:
                id: coreos.ociarchive
                url:
                  mpp-format-string: 'file://{ociarchive}'
          options:
            paths:
              - from:
                  mpp-format-string: input://inlinefile/{embedded['coreos.ociarchive']}
                to: tree:///coreos.ociarchive
        else:
          type: org.osbuild.noop
  # Construct a tree here that is a representation of the filesystem
  # that you would see on a running OSTree system. i.e. instead of just
  # /ostree and /sysroot at the toplevel we see /usr/ /var/ /etc/ ... that
  # you would see inside an OSTree deployment. Having the plain files accessible
  # allows for this pipeline to be used as a buildroot for some stages
  # or as inputs for others (i.e. file_context input to the org.osbuild.selinux
  # stages). This pipeline isn't actually used for built artifacts but
  # to help during build.
  #
  # NOTE: this is only used as a buildroot on RHCOS (FCOS doesn't ship python).
  - name: deployed-tree
    stages:
      - mpp-if: ociarchive != ''
        then:
          type: org.osbuild.container-deploy
          inputs:
            images:
              type: org.osbuild.containers
              origin: org.osbuild.pipeline
              references:
                name:oci-archive:
                  name: coreos.ociarchive
        else:
          type: org.osbuild.container-deploy
          inputs:
            images:
              type: org.osbuild.containers-storage
              origin: org.osbuild.source
              mpp-resolve-images:
                images:
                  - source: $container_repo
                    tag: $container_tag
  # Build up the filesystem tree used to construct disk images later.
  - name: tree
    build:
      mpp-format-string: '{buildroot}'
    source-epoch: 1659397331
    stages:
      # Set the context of the root of the tree so that we avoid unlabeled_t files.
      # https://github.com/coreos/fedora-coreos-tracker/issues/1772
      - type: org.osbuild.selinux
        options:
          file_contexts: input://tree/etc/selinux/targeted/contexts/files/file_contexts
          target: tree:///
        inputs:
          tree:
            type: org.osbuild.tree
            origin: org.osbuild.pipeline
            references:
              - name:deployed-tree
      - type: org.osbuild.ostree.init-fs
      - type: org.osbuild.ostree.os-init
        options:
          osname:
            mpp-format-string: '{osname}'
      - type: org.osbuild.ostree.config
        options:
          repo: /ostree/repo
          config:
            sysroot:
              readonly: true
              bootloader: none
              # https://github.com/coreos/fedora-coreos-tracker/issues/1333
              # no grub_users="" on s390x
              bls-append-except-default:
                mpp-if: arch != 's390x'
                then: 'grub_users=""'
              # Opt-in to https://github.com/ostreedev/ostree/pull/2705 which will
              # add /boot as the prefix on top of BLS config entries. This is OK
              # because there is a symlink that is created in the root of the boot
              # filesystem by OSTree (boot -> .) that makes it so that /boot paths
              # will always work.
              bootprefix: true
      # Create /boot/efi mountpoint on EFI architectures
      - mpp-if: arch in ['x86_64', 'aarch64', 'riscv64']
        then:
          type: org.osbuild.mkdir
          options:
            paths:
              - path: /boot/efi
                mode: 493
      - type: org.osbuild.ignition
      # Deploy via ociarchive or container
      - type: org.osbuild.ostree.deploy.container
        options:
          osname:
            mpp-format-string: '{osname}'
          target_imgref:
            mpp-format-string: '{container_imgref}'
          mounts:
            - /boot
            # Mount /boot/efi on EFI architectures
            - mpp-if: arch in ['x86_64', 'aarch64', 'riscv64']
              then: /boot/efi
          kernel_opts:
            - rw
            # '$ignition_firstboot' only works with GRUB, not available on s390x
            - mpp-if: arch != 's390x'
              then: '$ignition_firstboot'
            - mpp-format-string: '{extra_kargs}'
        inputs:
          images:
            mpp-if: ociarchive != ''
            then:
              type: org.osbuild.containers
              origin: org.osbuild.pipeline
              references:
                name:oci-archive:
                  name: coreos.ociarchive
            else:
              type: org.osbuild.containers-storage
              origin: org.osbuild.source
              mpp-resolve-images:
                images:
                  - source: $container_repo
                    tag: $container_tag
      # Drop the immutable bit here (we add it back later) because it
      # causes failures when cleaning up tmp dirs.
      - mpp-if: arch in ['ppc64le', 's390x']
        then:
          type: org.osbuild.chattr
          options:
            items:
              tree:///:
                immutable: false
          mounts:
            - name: ostree.deployment
              type: org.osbuild.ostree.deployment
              options:
                deployment:
                  default: true
      # On s390x set the bootloader to zipl. We need to do it here
      # rather than in the ostree.config stage above because we don't want
      # OSTree to invoke zipl during the deploy. It's done later in zipl.inst.
      - mpp-if: arch == 's390x'
        then:
          type: org.osbuild.ostree.config
          options:
            repo: /ostree/repo
            config:
              sysroot:
                bootloader: zipl
      - type: org.osbuild.ostree.aleph
        options:
          coreos_compat: true
          deployment:
            default: true
      - type: org.osbuild.ostree.selinux
        options:
          deployment:
            default: true
