# This file defines the raw-image pipeline that leverages bootc install.
version: '2'
pipelines:
  - name: raw-image
    build:
      mpp-format-string: '{buildroot}'
    stages:
      - type: org.osbuild.truncate
        options:
          filename: disk.img
          size:
            mpp-format-string: '{image.size}'
      - type: org.osbuild.sfdisk
        devices:
          device:
            type: org.osbuild.loopback
            options:
              filename: disk.img
        options:
          mpp-format-json: '{image.layout}'
      # Create EFI filesystem on EFI architectures
      - mpp-if: arch in ['x86_64', 'aarch64', 'riscv64']
        then:
          type: org.osbuild.mkfs.fat
          devices:
            device:
              type: org.osbuild.loopback
              options:
                filename: disk.img
                start:
                  mpp-format-int: '{image.layout[''EFI-SYSTEM''].start}'
                size:
                  mpp-format-int: '{image.layout[''EFI-SYSTEM''].size}'
                lock: true
          options:
            label: EFI-SYSTEM
            volid: 7B7795E7
      - type: org.osbuild.mkfs.ext4
        devices:
          device:
            type: org.osbuild.loopback
            options:
              filename: disk.img
              start:
                mpp-format-int: '{image.layout[''boot''].start}'
              size:
                mpp-format-int: '{image.layout[''boot''].size}'
              lock: true
        options:
          uuid:
            mpp-format-string: '{boot_fs_uuid}'
          label:
            mpp-format-string: '{boot_fs_label}'
          # Set manually the metadata_csum_seed ext4 option otherwise changing the
          # filesystem UUID while it's mounted doesn't work. Can remove this when
          # metadata_csum_seed is default in RHEL, which can be checked by looking
          # in /etc/mke2fs.conf.
          metadata_csum_seed: true
      - type: org.osbuild.mkfs.xfs
        devices:
          device:
            type: org.osbuild.loopback
            options:
              filename: disk.img
              start:
                mpp-format-int: '{image.layout[''root''].start}'
              size:
                mpp-format-int: '{image.layout[''root''].size}'
              lock: true
        options:
          agcount:
            mpp-format-int: '{root_fs_agcount}'
          uuid:
            mpp-format-string: '{root_fs_uuid}'
          label:
            mpp-format-string: '{root_fs_label}'
      # We've created the filesystems. Now let's create the mountpoints (directories)
      # on the filesystems and label them with appropriate SELinux labels. This also
      # covers things like filesystem autogenerated files like 'lost+found'. The labeling
      # will happen once with just the root filesystem mounted and once with the boot
      # filesystem mounted too (to make sure we get all potentially hidden mountpoints).
      # https://github.com/coreos/fedora-coreos-tracker/issues/1771
      - type: org.osbuild.mkdir
        options:
          paths:
            - path: mount://root/boot
              mode: 493
            # Create /boot/efi mountpoint on EFI architectures
            - mpp-if: arch in ['x86_64', 'aarch64', 'riscv64']
              then:
                path: mount://boot/efi
                mode: 493
        devices:
          disk:
            type: org.osbuild.loopback
            options:
              filename: disk.img
              partscan: true
        mounts:
          - name: root
            type: org.osbuild.xfs
            source: disk
            partition:
              mpp-format-int: '{image.layout[''root''].partnum}'
            target: /root-mount-point
          # Mount boot partition on EFI architectures for /boot/efi creation
          - mpp-if: arch in ['x86_64', 'aarch64', 'riscv64']
            then:
              name: boot
              type: org.osbuild.ext4
              source: disk
              partition:
                mpp-format-int: '{image.layout[''boot''].partnum}'
              target: /boot-mount-point
      # Set the context of the root of disk so that we avoid unlabeled_t files.
      # Here we make sure to not mount the boot partition because we want to label
      # the directory mount point
      # https://github.com/coreos/fedora-coreos-tracker/issues/1772
      - type: org.osbuild.selinux
        options:
          file_contexts: input://tree/etc/selinux/targeted/contexts/files/file_contexts
          target: mount://root/
        inputs:
          tree:
            type: org.osbuild.tree
            origin: org.osbuild.pipeline
            references:
              - name:deployed-tree
        devices:
          disk:
            type: org.osbuild.loopback
            options:
              filename: disk.img
              partscan: true
        mounts:
          - name: root
            type: org.osbuild.xfs
            source: disk
            partition:
              mpp-format-int: '{image.layout[''root''].partnum}'
            target: /
      # Then we mount the boot parition and label again so the /boot/efi
      # mount point is labeled properly
      - type: org.osbuild.selinux
        options:
          file_contexts: input://tree/etc/selinux/targeted/contexts/files/file_contexts
          target: mount://root/boot/
        inputs:
          tree:
            type: org.osbuild.tree
            origin: org.osbuild.pipeline
            references:
              - name:deployed-tree
        devices:
          disk:
            type: org.osbuild.loopback
            options:
              filename: disk.img
              partscan: true
        mounts:
          - name: root
            type: org.osbuild.xfs
            source: disk
            partition:
              mpp-format-int: '{image.layout[''root''].partnum}'
            target: /
          - name: boot
            type: org.osbuild.ext4
            source: disk
            partition:
              mpp-format-int: '{image.layout[''boot''].partnum}'
            target: /boot
      # Use bootc install to-filesystem to install the ostree content from the container image
      # inside our disc image
      - type: org.osbuild.bootc.install-to-filesystem
        inputs: 
          images:
            mpp-if: ociarchive != ''
            then:
              type: org.osbuild.containers
              origin: org.osbuild.pipeline
              references:
                name:oci-archive:
                  name: coreos.ociarchive
            else:
              type: org.osbuild.containers-storage
              origin: org.osbuild.source
              mpp-resolve-images:
                images:
                  - source: $container_repo
                    tag: $container_tag
        options:
          kernel-args:
            # '$ignition_firstboot' only works with GRUB, not available on s390x
            - mpp-if: arch != 's390x'
              then: '$ignition_firstboot'
            - mpp-format-string: '{extra_kargs}'
          target-imgref:
            mpp-format-string: '{container_imgref}'
          stateroot:
            mpp-format-string: '{osname}'
          # Empty strings mean mount spec kargs are ommited entirely.
          # See github.com/bootc-dev/bootc/issues/1441
          boot-mount-spec: ""
          root-mount-spec: ""
        devices:
          disk:
            type: org.osbuild.loopback
            options:
              filename: disk.img
              partscan: true
        mounts:
          - name: root
            type: org.osbuild.xfs
            source: disk
            partition:
              mpp-format-int: '{image.layout[''root''].partnum}'
            target: /
          - name: boot
            type: org.osbuild.ext4
            source: disk
            partition:
              mpp-format-int: '{image.layout[''boot''].partnum}'
            target: /boot
          # Mount EFI partition on EFI architectures
          - mpp-if: arch in ['x86_64', 'aarch64', 'riscv64']
            then:
              name: efi
              type: org.osbuild.fat
              source: disk
              partition:
                mpp-format-int: '{image.layout[''EFI-SYSTEM''].partnum}'
              target: /boot/efi
      # set up the `ignition.firstboot` stamp at the end because
      # bootc want empty filesystems
      - type: org.osbuild.ignition
        options:
          target: mount://boot/
        devices:
          disk:
            type: org.osbuild.loopback
            options:
              filename: disk.img
              partscan: true
        mounts:
          - name: root
            type: org.osbuild.xfs
            source: disk
            partition:
              mpp-format-int: '{image.layout[''root''].partnum}'
            target: /
          - name: boot
            type: org.osbuild.ext4
            source: disk
            partition:
              mpp-format-int: '{image.layout[''boot''].partnum}'
            target: /boot
