version: '2'
mpp-vars:
  artifact_name_prefix: $artifact_name_prefix
  ociarchive: $ociarchive
  osname: $osname
  container_imgref: $container_imgref
  container_repo: $container_repo
  container_tag: $container_tag
  extra_kargs: $extra_kargs
  use_bootc_install: $use_bootc_install
  metal_image_size_mb: $metal_image_size_mb
  cloud_image_size_mb: $cloud_image_size_mb
  bios_boot_size_mb: 1
  ppc_prep_size_mb: 4
  reserved_part_size_mb: 1
  efi_system_size_mb: 127
  se_size_mb:   200
  boot_size_mb: 384
  boot_verity_size_mb: 128
  root_verity_size_mb: 256
  sector_size: 512
  four_k_sector_size: 4096
  # Filesystem UUID and label definitions. These UUIDs
  # are looked for on boot and if found replaced with
  # a new random UUID to make each install unique.
  sd_fs_label: se
  boot_fs_uuid: 96d15588-3596-4b3c-adca-a2ff7279ea63
  boot_fs_label: boot
  root_fs_uuid: 910678ff-f77e-4a7d-8d53-86f2ac47a823
  root_fs_label: root
  # The agcount of the XFS root filesystem. Set this to a smaller value
  # than the default (4) so we grown filesystems (most of our user
  # base) will have a lower overall agcount for their grown filesystem.
  # See https://github.com/coreos/fedora-coreos-tracker/issues/1993
  root_fs_agcount: 2
  # For some stages (i.e. the qemu stages) we'll use the host as
  # the buildroot (i.e. COSA in most cases but sometimes just
  # the actual HOST filesystem like in coreos/custom-coreos-disk-images).
  # This is useful/necessary because we definitely don't include
  # qemu-img or tools like zip in the actual CoreOS OS. "" here
  # means to use the host as buildroot. It is worth noting that
  # the host buildroot is the default if nothing is specified.
  # We're still defining it here in an attempt to be explicit.
  host_as_buildroot: ""
  # Set the buildroot string to use for most operations here. We create
  # the buildroot from the target OSTree contents so we have version
  # matches.
  buildroot: "name:deployed-tree"
  # Set the names of the files to use to import raw and raw4k pipelines
  raw_image_pipeline_file:
    mpp-if: use_bootc_install == 'true'
    then: "build.raw-image-bootc.ipp.yaml"
    else: "build.raw-image.ipp.yaml"
  raw_4k_image_pipeline_file:
    mpp-if: use_bootc_install == 'true'
    then: "build.raw-4k-image-bootc.ipp.yaml"
    else: "build.raw-4k-image.ipp.yaml"
mpp-define-images:
  - id: image
    sector_size:
        mpp-format-int: "{sector_size}"
    size:
      mpp-format-string: "{metal_image_size_mb * 1024 * 1024}"
    table:
      uuid: 00000000-0000-4000-a000-000000000001
      label: gpt
      partitions:
        - name: boot
          type: BC13C2FF-59E6-4262-A352-B275FD6F7172
          size:
            mpp-format-int: "{boot_size_mb * 1024 * 1024 / sector_size}"
          partnum: 3
        - name: root
          type: 5EEAD9A9-FE09-4A1E-A1D7-520D00531306
          partnum: 4
  - id: image4k
    sector_size:
        mpp-format-int: "{four_k_sector_size}"
    size:
      mpp-format-string: "{metal_image_size_mb * 1024 * 1024}"
    table:
      uuid: 00000000-0000-4000-a000-000000000001
      label: gpt
      partitions:
        - name: boot
          type: BC13C2FF-59E6-4262-A352-B275FD6F7172
          size:
            mpp-format-int: "{boot_size_mb * 1024 * 1024 / four_k_sector_size}"
          partnum: 3
        - name: root
          type: 5EEAD9A9-FE09-4A1E-A1D7-520D00531306
          partnum: 4
pipelines:
  - mpp-import-pipelines:
      path: build.common.ipp.yaml
  - mpp-import-pipelines:
      path: $raw_image_pipeline_file
  - mpp-import-pipelines:
      path: $raw_4k_image_pipeline_file
  - mpp-import-pipelines:
      path: platform.ibmcloud.ipp.yaml
  - mpp-import-pipelines:
      path: platform.metal.ipp.yaml
  - mpp-import-pipelines:
      path: platform.openstack.ipp.yaml
  - mpp-import-pipelines:
      path: platform.qemu.ipp.yaml
  - mpp-import-pipelines:
      path: platform.qemu-secex.ipp.yaml
  - mpp-import-pipelines:
      path: platform.live.ipp.yaml
  - mpp-import-pipelines:
      path: platform.kubevirt.ipp.yaml
