# This file isn't yet being used today but holds an OSBuild image
# definition for the hyperv platform.
version: '2'
pipelines:
  - name: raw-hyperv-image
    stages:
      - type: org.osbuild.copy
        inputs:
          tree:
            type: org.osbuild.tree
            origin: org.osbuild.pipeline
            references:
              - name:raw-image
        options:
          paths:
            - from: input://tree/disk.img
              to: tree:///disk.img
      # Increase the size to the cloud image size
      - type: org.osbuild.truncate
        options:
          filename: disk.img
          size:
            mpp-format-string: "{cloud_image_size_mb * 1024 * 1024}"
      - type: org.osbuild.kernel-cmdline.bls-append
        options:
          bootpath: mount:///
          kernel_opts:
            - ignition.platform.id=hyperv
        devices:
          boot:
            type: org.osbuild.loopback
            options:
              filename: disk.img
              start:
                mpp-format-int: '{image.layout[''boot''].start}'
              size:
                mpp-format-int: '{image.layout[''boot''].size}'
        mounts:
          - name: boot
            type: org.osbuild.ext4
            source: boot
            target: /
  - name: hyperv
    stages:
      - type: org.osbuild.qemu
        inputs:
          image:
            type: org.osbuild.files
            origin: org.osbuild.pipeline
            references:
              name:raw-hyperv-image:
                file: disk.img
        options:
          filename:
            mpp-format-string: '{filename}'
          format:
            type: vhdx
