# This file isn't yet being used today but holds an OSBuild image
# definition for the applehv platform.
version: '2'
pipelines:
  - name: raw-applehv-image
    stages:
      - type: org.osbuild.copy
        inputs:
          tree:
            type: org.osbuild.tree
            origin: org.osbuild.pipeline
            references:
              - name:raw-image
        options:
          paths:
            - from: input://tree/disk.img
              to: tree:///disk.img
      # Increase the size to the cloud image size
      - type: org.osbuild.truncate
        options:
          filename: disk.img
          size:
            mpp-format-string: "{cloud_image_size_mb * 1024 * 1024}"
      - type: org.osbuild.coreos.platform
        options:
          platform: applehv
        devices:
          disk:
            type: org.osbuild.loopback
            options:
              filename: disk.img
              partscan: true
        mounts:
           - name: root
             type: org.osbuild.xfs
             source: disk
             partition:
               mpp-format-int: '{image.layout[''root''].partnum}'
             target: /
           - name: ostree.deployment
             type: org.osbuild.ostree.deployment
             options:
               source: mount
               deployment:
                 default: true
           - name: boot
             type: org.osbuild.ext4
             source: disk
             partition:
               mpp-format-int: '{image.layout[''boot''].partnum}'
             target: /boot
  - name: applehv
    stages:
      - type: org.osbuild.copy
        inputs:
          tree:
            type: org.osbuild.tree
            origin: org.osbuild.pipeline
            references:
              - name:raw-applehv-image
        options:
          paths:
            - from: input://tree/disk.img
              to:
                mpp-format-string: 'tree:///{filename}'
