#!/bin/bash -xe
mydir=$(readlink -f $(dirname $(basename $0)))
pdir=$(dirname ${mydir})

tdir="${mydir}/tmp"
mkdir -p "${tdir}"
trap "rm -rfv ${tdir}" EXIT

export GOBIN="bin"
mkdir -p ${GOBIN}
if [ ! -x "${GOBIN}/schematyper" ]; then
    make
fi

schema_version="v1"
schema_json="../src/schema/${schema_version}.json"
echo "Generating COSA Schema ${schema_version}"

out="${tdir}/cosa_${schema_version}.go"

"${GOBIN}/schematyper" \
    "../src/schema/${schema_version}.json" \
    -o "${out}" \
    --package="cosa" \
    --root-type=Build \
    --ptr-for-omit

# Avoid having a filename in generated code since it
# can vary depending on local checkout paths.
sed -e "s|^// generated.*|// generated by 'make schema'|g"  -i ${tdir}/cosa_v1.go

cat > "${tdir}/schema_doc.go" <<EOM
// Generated by ${0}
// DO NOT EDIT

package cosa

var generatedSchemaJSON = \`$(< ${schema_json})
\`
EOM

cp -av ${out} ${pdir}/gangplank/cosa/
cp -av ${tdir}/*go ${pdir}/mantle/cosa/

