#!/usr/bin/env bash
set -euo pipefail

dn=$(dirname "$0")
# shellcheck source=src/cmdlib.sh
. "${dn}"/cmdlib.sh

commit=$1
shift
tmpdir=$1
shift

sudo() {
    if [ "$(id -u)" != 0 ]; then
        /usr/bin/sudo -E "$@"
    else
        "$@"
    fi
}

if has_privileges; then
    # Avoid using the builddir inside the VM, since rpmbuild will fail
    # to preserve permissions in `mv`
    orig_tmpdir=
    if [ -f /etc/cosa-supermin ]; then
        orig_tmpdir="${tmpdir}"
        tmpdir=$(mktemp -d -p /var/tmp)
    fi
    sudo rpm-ostree ex commit2rojig --repo="$(pwd)/tmp/repo" --pkgcache-repo="$(pwd)/cache/pkgcache-repo" \
        "${commit}" "$(pwd)/src/config/manifest.yaml" "${tmpdir}"
    if ! [ -f /etc/cosa-supermin ]; then
        sudo chown -R -h "${USER}:${USER}" "${tmpdir}"
    else
        cp -r --preserve=mode "${tmpdir}"/* "${orig_tmpdir}"/
    fi
else
    info "Required privileges not detected; running via supermin appliance"
    prepare_build
    runvm -drive "if=none,id=cache,discard=unmap,file=${workdir}/cache/cache2.qcow2" \
            -device virtio-blk,drive=cache -- "${0}" "${commit}" "${tmpdir}"
fi
