#!/bin/bash
set -euo pipefail

srcdir=$1; shift
name=$1; shift
outdir=$1; shift

sha256=$(cd "${srcdir}" && find . ! -type d -print0 | xargs -0 -r sha256sum \
            | sha256sum | cut -f 1 -d ' ')

latest_rpm=$(find "$outdir/" -iname "$name-*.rpm" | sort -Vr | head -n 1)

if rpm -qp "$latest_rpm" --qf '%{DESCRIPTION}' | grep -q "(sha256:$sha256)"; then
    echo "Re-using ${latest_rpm} ($sha256)."
    exit 0
fi

# shellcheck disable=SC2154
cat > "$name.spec" << EOF
Name: $name
Version: $(date +%s)
Release: ${sha256::7}
BuildArch: noarch
Summary: $summary overlay
License: $license
# this shows up then in rpm -qi (XXX: don't hardcode this)
URL: https://github.com/coreos/fedora-coreos-config

BuildRequires: rsync

%description
%{summary} (sha256:$sha256)

%build
# Nothing to build

%install
rsync -av "${srcdir}/" %{buildroot}

%files
$(cd "${srcdir}" && find . ! -type d | cut -c 2-)
EOF

rm -rf rpms
rpmbuild -ba \
  --define "_sourcedir $PWD" \
  --define "_specdir $PWD" \
  --define "_builddir $PWD/.build" \
  --define "_srcrpmdir $PWD/rpms" \
  --define "_rpmdir $PWD/rpms" \
  --define "_buildrootdir $PWD/.buildroot" "$name.spec"

# delete any older RPMs first
rm -f "$outdir/$name"-*.rpm
cp rpms/noarch/*.rpm "$outdir"
