#!/usr/bin/env bash
set -euo pipefail

dn=$(dirname "$0")
# shellcheck source=src/cmdlib.sh
. "${dn}"/cmdlib.sh

print_help() {
    cat 1>&2 <<'EOF'
Usage: coreos-assembler build-with-buildah
       coreos-assembler build-with-buildah [OPTIONS]...

  Build bootable container (ostree) and image base artifacts using the container runtime (buildah).
  `cosa build` will pivot to this script when the environment variable `COREOS_ASSEMBLER_BUILD_WITH_BUILDAH` is set.

  The following options are supported:
  --version=VERSION      Use the given version instead of using versionary.
  --versionary           Generate non-development version using versionary.
  --direct               Run buildah directly rather than within supermin.
  --autolock=VERSION     If no base lockfile used, create one from any arch build of `VERSION`.
                         Note this is automatically enabled when adding to an existing multi-arch
                         non-strict build.
  --skip-prune           Skip prunning previous builds
  --parent-build=VERSION This option does nothing and is provided for backwards compatibility.
  --force                This option does nothing and is provided for backwards compatibility.
EOF
}

VERSION=
VERSIONARY=
DIRECT=
AUTOLOCK_VERSION=
SKIP_PRUNE=
rc=0
options=$(getopt --options h,d --longoptions help,version:,versionary,direct,autolock:,skip-prune,parent-build:,force -- "$@") || rc=$?
[ $rc -eq 0 ] || {
    print_help
    exit 1
}
eval set -- "$options"
while true; do
    case "$1" in
        -h | --help)
            print_help
            exit 0
            ;;
        --version)
            shift
            VERSION=$1
            ;;
        --versionary)
            VERSIONARY=1
            ;;
        -d | --direct)
            DIRECT=1
            ;;
        --autolock)
            shift;
            AUTOLOCK_VERSION=$1
            ;;
        --skip-prune)
            SKIP_PRUNE=1
            ;;
        --parent-build)
            shift
            ;;
        --force)
            ;;
        --)
            shift
            break
            ;;
        -*)
            fatal "$0: unrecognized option: $1"
            ;;
        *)
            break
            ;;
    esac
    shift
done

if [ -z "${VERSION}" ]; then
    # let error out if file does not exist
    if [ -z "${VERSIONARY}" ]; then
        VERSION=$(src/config/versionary --dev)
    else
        VERSION=$(src/config/versionary)
    fi
fi

build_with_buildah() {
    echo "Building with container runtime (buildah) with VERSION=${VERSION}..."

    tempdir=$(mktemp -d --tmpdir=tmp "build-with-buildah.XXXXXXXX")

    # the config dir virtiofs mount is mounted ro; copy it to the tempdir
    cp -r src/config/ "${tempdir}/src"
    # Make sure there are no setgid/setuid bits in there.
    # See e.g. https://github.com/coreos/fedora-coreos-tracker/issues/1003.
    # This is analogous to the chmod we do in cmdlib.sh in the legacy path.
    chmod -R gu-s "${tempdir}/src"

    tmp_oci_archive_path=$(realpath "${tempdir}/out.ociarchive")

    initconfig="src/config.json"
    if [ -f "${initconfig}" ]; then
        variant="$(jq --raw-output '."coreos-assembler.config-variant"' "${initconfig}")"
        manifest="src/config/manifest-${variant}.yaml"
        argsfile=build-args-${variant}.conf
    else
        manifest="src/config/manifest.yaml"
        argsfile=build-args.conf
    fi

    if [ -e "builds/$VERSION/${arch}" ]; then
        echo "Build ${VERSION} ($arch) already exists"
        exit 0
    fi

    # Apply autolock from another build for this version (or for another version if
    # explicitly provided via --autolock) if no base lockfile exists.
    lockfile="manifest-lock.${arch}.json"
    if [ ! -f "src/config/${lockfile}" ] && { [ -n "${VERSION}" ] || [ -n "${AUTOLOCK_VERSION}" ]; }; then
        autolockfile=$(tmprepo=tmp/repo; workdir=.;
                       ostree init --repo="${tmprepo}" --mode=archive;
                       generate_autolock "${AUTOLOCK_VERSION:-${VERSION}}")
        if [ -n "${autolockfile}" ]; then
            echo "Injecting autolock-generated ${lockfile}..."
            cp "${autolockfile}" "${tempdir}/src/${lockfile}"
        fi
    fi

    # Here we call prepare_git_artifacts just for its git logic, We don't
    # actually care about the JSON file; the source of truth is in the labels.
    prepare_git_artifacts src/config "${tempdir}/coreos-assembler-config-git.json"
    source=$(jq -r .git.origin "${tempdir}/coreos-assembler-config-git.json")
    commit=$(jq -r .git.commit "${tempdir}/coreos-assembler-config-git.json")
    rm -f "${tempdir}/coreos-assembler-config-git.json"

    # For the source: check if there's only one remote, if so use it with get-url
    # For revision: rev-parse
    set -- build --security-opt=label=disable --cap-add=all --device /dev/fuse \
            --build-arg-file "$argsfile" -v "$(realpath "${tempdir}/src")":/run/src \
            --build-arg VERSION="${VERSION}" \
            --label org.opencontainers.image.source="${source}" \
            --label org.opencontainers.image.revision="${commit}"

    # XXX: Temporary hack until we have https://github.com/coreos/rpm-ostree/pull/5454
    # which would allow us to fold this back into the build process.
    # shellcheck source=/dev/null
    stream=$(yaml2json "$manifest" /dev/stdout | jq -r '.variables.stream')
    if [ "${stream}" != null ]; then
        set -- "$@" --label fedora-coreos.stream="$stream" \
                    --annotation fedora-coreos.stream="$stream"
    fi

    if [ -d "src/yumrepos" ] && [ -e "src/yumrepos/${variant:-}.repo" ]; then
        set -- "$@" --secret id=yumrepos,src="$(realpath "src/yumrepos/$variant.repo")" \
                    --secret id=contentsets,src="$(realpath src/yumrepos/content_sets.yaml)" \
                    -v /etc/pki/ca-trust:/etc/pki/ca-trust:ro
    fi

    if [ -d overrides ]; then
        if [ -d overrides/rpm ]; then
            # Clean up any previous repo metadata
            rm -rf overrides/rpm/repodata
            if [[ -n $(ls overrides/rpm/*.rpm 2> /dev/null) ]]; then
                # Generate new repo metadata since there are RPMs
                (cd overrides/rpm && createrepo_c .)
            fi
        fi
        set -- "$@" -v "$(realpath overrides)":/run/src/overrides
    fi

    if [ -n "$DIRECT" ]; then
        # turn on layer caching in the direct case; it wouldn't hurt in the
        # supermin path, but it'd be a waste of space on the rootfs
        set -- "$@" --layers=true
        # output to a tag since it's more convenient for development;
        # buildah doesn't support doing both at once
        # shellcheck disable=SC1090
        osname=$(source "src/config/${argsfile}"; echo "${NAME}")
        final_ref="containers-storage:localhost/${osname}:${VERSION}"
    else
        # In the supermin path ensure the ociarchive gets compressed
        set -- "$@" --disable-compression=false
        final_ref="oci-archive:${tmp_oci_archive_path}"
    fi

    # and finally, add the tag and context dir
    set -- "$@" -t "${final_ref}" .

    echo "Running:" buildah "$@"
    if [ -n "$DIRECT" ]; then
        env -C "${tempdir}/src" buildah "$@"
    else
        /usr/lib/coreos-assembler/cmd-supermin-run --cache \
            env -C "${tempdir}/src" TMPDIR="$(realpath cache)" buildah "$@"
    fi

    /usr/lib/coreos-assembler/cmd-import "${final_ref}" ${SKIP_PRUNE:+--skip-prune}

    rm -rf "${tempdir}"
}

build_with_buildah
