#!/usr/bin/env bash
set -euo pipefail

dn=$(dirname "$0")
# shellcheck source=src/cmdlib.sh
. "${dn}"/cmdlib.sh

print_help() {
    cat 1>&2 <<'EOF'
Usage: coreos-assembler bump-timestamp

  Update the `timestamp` key of `builds.json`.
EOF
}

if [ $# -ne 0 ]; then
    print_help
    fatal "ERROR: Too many arguments"
    exit 1
fi

prepare_build

"${dn}"/prune_builds --timestamp-only --workdir "${workdir:?}"
