#!/usr/bin/env bash
set -euo pipefail

if [ $# -eq 0 ]; then
    # If no arguments then offer user bash prompt inside the container
    exec /usr/bin/env PS1='[coreos-assembler]$ ' /usr/bin/bash
else
    # They provided arguments so just run the command
    exec "$@"
fi
