#!/usr/bin/env bash
set -euo pipefail

dn=$(dirname "$0")
# shellcheck source=src/cmdlib.sh
. "${dn}"/cmdlib.sh

print_help() {
    cat 1>&2 <<'EOF'
Usage: coreos-assembler fetch --help
       coreos-assembler fetch [--update-lockfile] [--write-lockfile-to=file]

  Fetch and import the latest packages.
EOF
}

UPDATE_LOCKFILE=
OUTPUT_LOCKFILE=
DRY_RUN=
rc=0
options=$(getopt --options h --longoptions help,update-lockfile,dry-run,write-lockfile-to: -- "$@") || rc=$?
[ $rc -eq 0 ] || {
    print_help
    exit 1
}
eval set -- "$options"
while true; do
    case "$1" in
        -h | --help)
            print_help
            exit 0
            ;;
        --update-lockfile)
            UPDATE_LOCKFILE=1
            ;;
        --write-lockfile-to)
            shift;
            UPDATE_LOCKFILE=1
            OUTPUT_LOCKFILE=$1
            ;;
        --dry-run)
            DRY_RUN=1
            ;;
        --)
            shift
            break
            ;;
        *)
            fatal "$0: unrecognized option: $1"
            exit 1
            ;;
    esac
    shift
done

if [ $# -ne 0 ]; then
    print_help
    fatal "ERROR: Too many arguments"
    exit 1
fi

prepare_build

args=
if [ -n "${UPDATE_LOCKFILE}" ]; then
    # Put this under tmprepo so it gets automatically chown'ed if needed
    args="--ex-write-lockfile-to=${tmprepo}/tmp/manifest-lock.json"
    if [ -f "${manifest_lock_overrides}" ]; then
        echo "NB: ignoring overrides ${manifest_lock_overrides}"
        sleep 1
    fi
else
    for lock in "${manifest_lock}" "${manifest_lock_overrides}"; do
        if [ -f "${lock}" ]; then
            args+=" --ex-lockfile=${lock}"
            echo "Fetching RPMs from lockfile: ${lock}"
        fi
    done
    if [ -n "${args}" ]; then
        sleep 1
    fi
fi

if [ -n "${DRY_RUN}" ]; then
    args="${args} --dry-run"
fi

# shellcheck disable=SC2086
runcompose --download-only ${args}

if [ -n "${UPDATE_LOCKFILE}" ]; then
    # Write out to the lockfile specified by the user or to the
    # existing manifest lockfile if none was specified by the user
    if [ -n "${OUTPUT_LOCKFILE}" ]; then
        # assume given path is relative to toplevel workdir
        outfile="${workdir}/${OUTPUT_LOCKFILE}"
    else
        outfile=$manifest_lock
    fi
    strip_out_lockfile_digests "${tmprepo}/tmp/manifest-lock.json"
    mv -f "${tmprepo}/tmp/manifest-lock.json" "${outfile}"
    echo "Wrote out lockfile ${outfile}"
fi
