#!/usr/bin/env bash
set -euo pipefail

dn=$(dirname "$0")
# shellcheck source=src/cmdlib.sh
. "${dn}"/cmdlib.sh

print_help() {
    cat 1>&2 <<'EOF'
Usage: coreos-assembler buildextend-metal --help
       coreos-assembler buildextend-metal [--build ID]

  Build a bare metal image.
EOF
}

# Parse options
rc=0
build=
options=$(getopt --options h --longoptions help,build: -- "$@") || rc=$?
[ $rc -eq 0 ] || {
    print_help
    exit 1
}
eval set -- "$options"
while true; do
    case "$1" in
        -h | --help)
            print_help
            exit 0
            ;;
        --build)
            build=$2
            shift
            ;;
        --)
            shift
            break
            ;;
        -*)
            fatal "$0: unrecognized option: $1"
            exit 1
            ;;
        *)
            break
            ;;
    esac
    shift
done

if [ $# -ne 0 ]; then
    print_help
    fatal "Too many arguments passed"
fi

case "$arch" in
    "x86_64"|"aarch64")
        ## fall through to the rest of the file
	;;
    *)
        echo "$arch is not supported for this command"
        exit 1
        ;;
esac

export LIBGUESTFS_BACKEND=direct

prepare_build

if [ -z "${build}" ]; then
    if [ -L "${workdir}"/builds/latest ]; then
        build=$(readlink "${workdir}"/builds/latest)
    else
        fatal "No build found."
    fi
fi

builddir="${workdir}/builds/${build}"
if [ ! -d "${builddir}" ]; then
    fatal "Build dir ${builddir} does not exist."
fi

json_key() {
    jq -r ".[\"$1\"]" < "${builddir}/meta.json"
}

# reread these values from the build itself rather than rely on the ones loaded
# by prepare_build since the config might've changed since then
name=$(json_key name)
ref=$(json_key ref)
ref_is_temp=""
if [ "${ref}" = "null" ]; then
    ref="tmpref-${name}"
    ref_is_temp=1
fi
commit=$(json_key ostree-commit)

ostree_repo=${tmprepo}
rev_parsed=$(ostree rev-parse --repo="${ostree_repo}" "${ref}" 2>/dev/null || :)
if [ "${rev_parsed}" != "${commit}" ]; then
    # Probably an older commit or tmp/ was wiped. Let's extract it to a separate
    # temporary repo (not to be confused with ${tmprepo}...) so we can feed it
    # as a ref (if not temp) to Anaconda.
    echo "Cache for build ${build} is gone"
    echo "Importing commit ${commit} into temporary OSTree repo"
    mkdir -p tmp/repo
    tar -C tmp/repo -xf "${builddir}/ostree-commit.tar"
    ostree_repo=$PWD/tmp/repo
    if [ -n "${ref_is_temp}" ]; then
        # this gets promptly "dereferenced" back in run_virtinstall, but it
        # keeps the code below simple so it can work in both temp/not temp cases
        ostree refs --repo="${ostree_repo}" "${commit}" --create "${ref}"
    fi # otherwise, the repo already has a ref, so no need to create
fi


img=${name}-${build}-metal.raw
if [ -f "${builddir}/${img}" ]; then
    echo "Bare metal image already exists"
    exit
fi

path=${PWD}/${img}

echo "Estimating disk size..."
/usr/lib/coreos-assembler/estimate-commit-disk-size --repo "$ostree_repo" "$ref" --add-percent 20 > "$PWD/tmp/ostree-size.json"
size="$(jq '."estimate-mb".final' "$PWD/tmp/ostree-size.json")"
# extra size is the non-ostree partitions, see create_disk.sh
size="$(( size + 513 ))M"
echo "Disk size estimated to $size"
kargs="$(python3 -c 'import sys, yaml; args = yaml.safe_load(sys.stdin)["extra-kargs"]; print(" ".join(args))' < "$configdir/image.yaml")"
kargs="$kargs console=tty0 console=${VM_TERMINAL},115200n8 ignition.platform.id=metal"

qemu-img create -f qcow2 "${path}.qcow2" "$size"
runvm_with_disk "${path}.qcow2" /usr/lib/coreos-assembler/create_disk.sh /dev/vda "$ostree_repo" "${ref-:${commit}}" /usr/lib/coreos-assembler/grub.cfg "$name" "\"$kargs\""
qemu-img convert "${path}.qcow2" "$path"
rm "${path}.qcow2"

# flush it out before going to the next one so we don't have to redo both if
# the next one fails

# there's probably a jq one-liner for this...
python3 -c "
import sys, json
j = json.load(sys.stdin)
j['images']['metal'] = {
    'path': '${img}',
    'sha256': '$(sha256sum_str < "${img}")',
    'size': $(stat -c '%s' "${img}")
}
json.dump(j, sys.stdout, indent=4)
" < "${builddir}/meta.json" > meta.json.new

# and now the crucial bit
mv -T meta.json.new "${builddir}/meta.json"
mv -T "${img}" "${builddir}/${img}"
