#!/usr/bin/python3 -u

import argparse
import logging
import sys
import tenacity

from cosalib.cmdlib import runcmd
from os import environ

# Set up logging
logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(levelname)s - %(message)s")

def build_container_image(labels, gitURL, gitRef, repo, tag):
    '''
    Build the image  using podman remote and push to the registry
    @param repo str registry repository
    @param tag  str image tag
    @param time str expiration time for Quay images
    '''
    cmd = ["podman", "--remote", "build", f"{gitURL}#{gitRef}", f"--tag={repo}:{tag}"]
    for label in labels:
        cmd.extend([f"--label={label}"])
    # Long running command. Send output to stdout for logging
    runcmd(cmd)

def push_container_image(repo, tag):
    '''
    Push image to registry
    @param repo str registry repository
    @param tag str image tag
    '''
    cmd = ["podman", "--remote", "push", f"{repo}:{tag}"]
    # Long running command. Send output to stdout for logging
    runcmd(cmd)
    # Quay seems to take some time to publish images in some occasions.
    # After the push let's wait for it to show up in the registry
    # before moving on.
    retryer = tenacity.Retrying(
        stop=tenacity.stop_after_delay(600),
        wait=tenacity.wait_fixed(15),
        retry=tenacity.retry_if_result(lambda x: x is False),
        before_sleep=tenacity.before_sleep_log(logging, logging.INFO))
    try:
        in_repo = retryer(is_tag_in_registry, repo, tag)
    except tenacity.RetryError:
        in_repo = False
    if in_repo:
        print(f"Build and Push done successfully via tag: {tag}")
    else:
        raise Exception(f"Image pushed but not viewable in registry: tag: {tag}")

def is_tag_in_podman_storage(repo, tag):
    '''
    Search for a tag in the local podman storage
    @param repo str registry repository
    @param tag  str image tag
    '''
    cmd = ["podman", "--remote", "image", "exists", f"{repo}:{tag}"]
    return runcmd(cmd, check=False, capture_output=True).returncode == 0

def is_tag_in_registry(repo, tag):
    '''
    Search for a tag in the registry
    @param repo str registry repository
    @param tag  str image tag
    '''
    # Podman remote doesn't allow push using digestfile. That's why the tag check is done
    cmd = ["podman", "search", "--list-tags", repo]
    tags = runcmd(cmd, capture_output=True).stdout.strip().decode()
    if (tag in str(tags)):
        return True
    return False

def main():
    # Arguments
    args = parse_args()
    # Check for requisite env vars
    if environ.get('CONTAINER_HOST') is None or environ.get('CONTAINER_SSHKEY') is None:
        sys.exit('You must have CONTAINER_HOST and CONTAINER_SSHKEY environment variables setup')
    # If a tag wasn't passed then use the git
    # short commit hash
    if not args.tag:
        cmd = ["git", "ls-remote", args.git_url, args.git_ref]
        commit = runcmd(cmd, capture_output=True).stdout.strip().decode()[0:7]
        args.tag = f"{args.arch}-{commit}"
    logging.info(f"Targetting a container image for {args.repo}:{args.tag}")
    # Sanity check the registry if asked to push to a registry
    if args.push_to_registry and is_tag_in_registry(args.repo, args.tag):
        logging.info(f"Container image at {args.repo}:{args.tag} exists.")
        if args.force:
            logging.info(f"--force was passed. Will overwrite container at {args.repo}:{args.tag}")
        else:
            logging.info("No work to do. You can force with --force. Skipping build/push.")
            return
    # Check first if the build already exists in local storage on the builder
    if is_tag_in_podman_storage(args.repo, args.tag):
        if args.force:
            logging.info(f"--force was passed. Will overwrite built container with tag {args.repo}:{args.tag}")
            needbuild = True
        else:
            logging.info(f"Re-using existing built container with tag {args.repo}:{args.tag}")
            needbuild = False
    else:
        needbuild = True
    # Build the container if needed.
    if needbuild:
        logging.info("Building container via podman")
        build_container_image(args.label, args.git_url, args.git_ref, args.repo, args.tag)
    # Push to the registry if needed
    if args.push_to_registry:
        logging.info("Pushing to remote registry")
        push_container_image(args.repo, args.tag)

def parse_args():
    parser = argparse.ArgumentParser(
        prog="CoreOS Assembler Remote Build",
        description="Build coreos-assembler remotely",
        usage="""
Run multi-arch builds using podman remote.
In order to get cmd-remote-build-container working the CONTAINER_SSHKEY and CONTAINER_HOST environment variables
must be defined

Examples:
    $ cosa remote-build-container \
        --arch aarch64 \
        --label quay.labels-after=4d \
        --git-ref main \
        --git-url https://github.com/coreos/coreos-assembler.git \
        --repo quay.io/coreos/coreos-assembler-staging \
        --push-to-registry """)

    parser.add_argument(
        '--arch', required=True,
        help='Build Architecture')
    parser.add_argument(
        '--label', default=[], action='append',
        required=False, help='Add image label(s)')
    parser.add_argument(
        '--force', required=False, action='store_true',
        help='Force image overwrite')
    parser.add_argument(
        '--git-ref', required=True,
        help='Git branch or tag')
    parser.add_argument(
        '--git-url', required=True,
        help='Git URL')
    parser.add_argument(
        '--push-to-registry', required=False, action='store_true',
         help='Push image to registry. You must be logged in before pushing images')
    parser.add_argument(
        '--repo', required=True,
        help='Registry repository')
    parser.add_argument(
        '--tag', required=False,
        help='Force image tag. The default is arch-commit')

    return parser.parse_args()


if __name__ == '__main__':
    sys.exit(main())
