#!/usr/bin/python3

'''
This command takes a containers-transports(5) ref to an OCI image and converts
it into a `cosa build`, as if one did `cosa build ostree`. One can then e.g.
`cosa buildextend-qemu` right away.
'''

import argparse
from dateutil import (parser, tz)
import json
import os
import subprocess
import tempfile
import shutil
import sys
from stat import (
    S_IREAD,
    S_IRGRP,
    S_IROTH)
from cosalib.builds import Builds
from cosalib.cmdlib import (
    rfc3339_time,
    get_basearch,
    sha256sum_file,
    import_oci_archive)
from cosalib.meta import GenericBuildMeta


def main():
    args = parse_args()

    # immediate inspect to error out early if it doesn't exists/we don't have ACLs and to do some upfront checks
    metadata = skopeo_inspect(args.srcimg)

    # let raise if missing
    assert metadata['Labels']['containers.bootc'] == '1'
    buildid = metadata['Labels']['org.opencontainers.image.version']

    builds = Builds()
    arch = get_basearch()
    if builds.has(buildid) and arch in builds.get_build_arches(buildid):
        print(f"ERROR: Build ID {buildid} ({arch}) already exists!")
        sys.exit(1)

    with tempfile.TemporaryDirectory(prefix='cosa-import-', dir='tmp') as tmpd:
        # create the OCI archive
        tmp_oci_archive = generate_oci_archive(args, tmpd)
        # extract the OCI manifest from it. Note here that we operate
        # on the ociarchive directly rather than args.srcimg because
        # otherwise the manifest we fetch with skopeo *could* be a
        # manifest list.
        tmp_oci_manifest = generate_oci_manifest(tmp_oci_archive, tmpd)

        # import into the tmp/repo to get the ostree-commit but also so it's cached
        ostree_commit = import_oci_archive(tmpd, 'tmp/repo', tmp_oci_archive, buildid)

        # create meta.json
        build_meta = generate_build_meta(tmp_oci_archive, tmp_oci_manifest, metadata, ostree_commit)

        # artificially recreate generated lockfile and commitmeta.json
        tmp_lockfile, tmp_commitmeta = generate_lockfile_and_commitmeta(tmpd, ostree_commit, build_meta)

        # move into official location
        finalize_build(builds, build_meta, tmp_oci_archive, tmp_oci_manifest, tmp_lockfile, tmp_commitmeta)

    # Now that the build has been created (i.e. files put into the
    # right places) let's use `cosa diff` to insert package and
    # advisory diffs into the meta.json and log the RPM diff, but
    # only if we have something to diff against.
    if args.parent_build or len(builds.get_builds()) > 1:
        starting_buildid = args.parent_build if args.parent_build else builds.get_previous()
        calculate_and_log_diffs(builds, buildid, arch, starting_buildid)

    if not args.skip_prune:
        subprocess.check_call(['/usr/lib/coreos-assembler/cmd-prune'])


def parse_args():
    parser = argparse.ArgumentParser(prog='cosa import')
    parser.add_argument("srcimg", metavar='IMAGE',
                        help="image to import (containers-transports(5) format)")
    parser.add_argument("--skip-prune", action='store_true',
                        help="Skip prunning previous builds")
    parser.add_argument("--parent-build",
                        help="The parent build to diff against")
    return parser.parse_args()


def generate_oci_archive(args, tmpd):
    tmpf = os.path.join(tmpd, 'out.ociarchive')

    if args.srcimg.startswith('oci-archive:'):
        print(f"Copying {args.srcimg.partition(':')[2]} to {tmpf}")
        shutil.copy(args.srcimg.partition(':')[2], tmpf)
    else:
        extra_args = []
        # in the containers-storage case, there's no digest to preserve
        if not args.srcimg.startswith('containers-storage'):
            extra_args += ['--preserve-digests']
        subprocess.check_call(['skopeo', 'copy', args.srcimg, f"oci-archive:{tmpf}"] + extra_args)
    return tmpf


def generate_oci_manifest(ociarchive, tmpd):
    tmpf = os.path.join(tmpd, 'oci-manifest.json')
    with open(tmpf, 'wb') as f:
        f.write(subprocess.check_output(["skopeo", "inspect", "--raw", f"oci-archive:{ociarchive}"]))
        os.fchmod(f.fileno(), S_IREAD | S_IRGRP | S_IROTH)
    return tmpf


def generate_lockfile_and_commitmeta(tmpd, ostree_commit, build_meta):
    tmp_lockfile = os.path.join(tmpd, 'lockfile.json')
    tmp_commitmeta = os.path.join(tmpd, 'commitmeta.json')
    out = subprocess.check_output(['rpm-ostree', 'db', 'list', '--repo', 'tmp/repo', ostree_commit], encoding='utf-8')
    rpmdb = {}
    pkglist = []
    ostree_linux = ""
    for line in out.splitlines():
        if not line.startswith(' '):
            continue
        n, ev, ra = line.strip().rsplit('-', 2)
        rpmdb[n] = {'evra': f'{ev}-{ra}'}

        if ':' in ev:
            e, v = ev.split(':')
        else:
            e, v = ("0", ev)
        r, a = ra.rsplit('.', 1)
        pkglist.append([n, e, v, r, a])
        if n == 'kernel':
            ostree_linux = f"{v}-{r}.{a}"

    commitmeta = {
        'coreos-assembler.config-gitrev': build_meta.get('coreos-assembler.container-config-git', {}).get('commit', ''),
        'coreos-assembler.basearch': build_meta.get('coreos-assembler.basearch', ''),
        'version': build_meta.get('buildid', ''),
        'ostree.bootable': True if build_meta.get('coreos-assembler.oci-imported-labels', {}).get('ostree.bootable', '0') == '1' else False,
        'ostree.linux': ostree_linux,
        'rpmostree.rpmdb.pkglist': pkglist,
        'synthetic': True,
    }

    stream = build_meta.get('coreos-assembler.oci-imported-labels', {}).get('fedora-coreos.stream', '')
    if stream != '':
        commitmeta['fedora-coreos.stream'] = stream

    with open(tmp_commitmeta, 'w') as f:
        json.dump(commitmeta, f, indent=2)

    with open(tmp_lockfile, 'w') as f:
        json.dump(fp=f, obj={
            'packages': rpmdb
        })

    return tmp_lockfile, tmp_commitmeta


def generate_build_meta(tmp_oci_archive, tmp_oci_manifest, metadata, ostree_commit):
    name = metadata['Labels']['com.coreos.osname']
    buildid = metadata['Labels']['org.opencontainers.image.version']
    created_timestamp = parse_timestamp(metadata['Created'])
    arch = get_basearch()

    meta = {
        'ostree-commit': ostree_commit,
        'ostree-version': buildid,
        'buildid': buildid,
        'name': name,
        'coreos-assembler.basearch': arch,
        'coreos-assembler.build-timestamp': created_timestamp,
        'coreos-assembler.oci-imported': True,
        'coreos-assembler.oci-imported-labels': metadata.get('Labels', {}),
        'ostree-timestamp': created_timestamp,
        'images': {
            'ostree': {
                "path": f"{name}-{buildid}-ostree.{arch}.ociarchive",
                "sha256": sha256sum_file(tmp_oci_archive),
                'size': os.path.getsize(tmp_oci_archive),
                "skip-compression": True
            },
            'oci-manifest': {
                'path': f'{name}-{buildid}-ostree.{arch}-manifest.json',
                'sha256': sha256sum_file(tmp_oci_manifest),
                'size': os.path.getsize(tmp_oci_manifest),
                "skip-compression": True,
            },
        },
    }

    # proxy build repo and commit to the standard cosa key
    source = metadata.get('Labels', {}).get('org.opencontainers.image.source')
    commit = metadata.get('Labels', {}).get('org.opencontainers.image.revision')
    if source and commit:
        meta['coreos-assembler.container-config-git'] = {
            'origin': source,
            'commit': commit,
        }

    summary = metadata.get('Labels', {}).get('org.opencontainers.image.description')
    if summary:
        meta['summary'] = summary

    # add a reference to ourselves as well
    try:
        with open('/cosa/coreos-assembler-git.json') as f:
            cosa_git = json.load(f)
            meta['coreos-assembler.container-image-git'] = cosa_git['git']
    except FileNotFoundError:
        pass

    return meta


def finalize_build(builds, build_meta, tmp_oci_archive, tmp_oci_manifest, tmp_lockfile, tmp_commitmeta):
    buildid = build_meta['buildid']
    arch = build_meta['coreos-assembler.basearch']

    destdir = f'builds/{buildid}/{arch}'
    os.makedirs(destdir)

    shutil.move(tmp_oci_archive, f'{destdir}/{build_meta['images']['ostree']['path']}')
    shutil.move(tmp_oci_manifest, f'{destdir}/{build_meta['images']['oci-manifest']['path']}')
    shutil.move(tmp_lockfile, f'{destdir}/manifest-lock.generated.{arch}.json')
    shutil.move(tmp_commitmeta, f'{destdir}/commitmeta.json')

    with open(f'{destdir}/meta.json', 'w') as f:
        json.dump(build_meta, f, indent=4)

    # and finally the real deal: insert the build and bump latest symlink
    builds.insert_build(buildid, arch)
    builds.bump_timestamp()

    if os.path.exists('builds/latest'):
        os.remove('builds/latest')
    os.symlink(f'{buildid}', 'builds/latest', target_is_directory=True)

    print(f'Imported OCI image as build {buildid}')


def calculate_and_log_diffs(builds, buildid, arch, starting_buildid):
    # Get the RPM/Advisory diff info
    diff_cmd_json = ['/usr/lib/coreos-assembler/cmd-diff', '--rpms-json',
                     '--from', starting_buildid, '--to', buildid]
    diff_json_str = subprocess.check_output(diff_cmd_json)
    diff_data = json.loads(diff_json_str)

    # Update the meta.json file with the RPM/Advisory diff info. Yes we
    # just created this file, but let's use the library now for access.
    meta = GenericBuildMeta(workdir=os.getcwd(), build=buildid, basearch=arch)
    meta.update({
        'pkgdiff': diff_data.get('pkgdiff'),
        'advisories-diff': diff_data.get('advisories')
    })
    meta.write()

    # For the logs let's output the RPM diff
    diff_cmd_log = ['/usr/lib/coreos-assembler/cmd-diff', '--rpms',
                    '--from', starting_buildid, '--to', buildid]
    subprocess.check_call(diff_cmd_log)


def skopeo_inspect(image):
    return json.loads(subprocess.check_output(['skopeo', 'inspect', '-n', image]))


def parse_timestamp(timestamp):
    timestamp = parser.parse(timestamp)
    return rfc3339_time(timestamp.astimezone(tz.UTC))


if __name__ == '__main__':
    main()
