#!/usr/bin/env bash
set -euo pipefail

dn=$(dirname $0)
. ${dn}/cmdlib.sh

# Initialize FORCE to 0
FORCE=0
SUBDIR=

print_help() {
    cat 1>&2 <<'EOF'
Usage: coreos-assembler init --help
       coreos-assembler init [--force] GITCONFIG [SUBDIR]

  For example, you can use https://github.com/coreos/fedora-coreos-config
  as GITCONFIG, or fork it.  Another option useful for local development
  (if you're running a shell inside this container) is to pass a file path
  starting with `/` - a symlink to it will be created and then used directly.

  If specified, SUBDIR is a subdirectory of the git repository that should
  contain manifest.yaml and image.ks.
EOF
}

# Call getopt to validate the provided input.
rc=0
options=$(getopt --options hf --longoptions help,force -- "$@") || rc=$?
[ $rc -eq 0 ] || {
    print_help
    exit 1
}
eval set -- "$options"
while true; do
    case "$1" in
    -h | --help)
        print_help
        exit 0
        ;;
    -f | --force)
        FORCE=1
        ;;
    --)
        shift
        break
        ;;
    *)
        print_help
        fatal "init: unrecognized option: $1"
        exit 1
        ;;
    esac
    shift
done

# If user did not provide a repo then error out
if [ $# = 0 ]; then
    print_help
    fatal "ERROR: Missing GITCONFIG"
    exit 1
fi

# If the current working dir is not empty then error out
# unless force provided
if [ "$FORCE" != "1" -a ! -z "$(ls -A ./)" ]; then
   fatal "init: current directory is not empty, override with --force"
fi

set -x
source=$1; shift
subdir=${1:-}

preflight

sudo chown $USER: .

INSTALLER=https://download.fedoraproject.org/pub/fedora/linux/releases/28/Everything/x86_64/iso/Fedora-Everything-netinst-x86_64-28-1.1.iso
INSTALLER_CHECKSUM=https://download.fedoraproject.org/pub/fedora/linux/releases/28/Everything/x86_64/iso/Fedora-Everything-28-1.1-x86_64-CHECKSUM

# Initialize sources (git)
mkdir -p src
(cd src
 if ! test -e config; then
     case "${source}" in
         /*) ln -sr "${source}/${subdir}" config;;
         *) git clone "${source}" config
            if [ -n "${subdir}" ]; then
                mv config config-git
                ln -sr config-git/${subdir} config
            fi
            ;;
     esac
     manifest=config/manifest.yaml
     if ! [ -f "${manifest}" ]; then
         echo 1>&2 "Failed to find src/${manifest}"
         fatal "If using a custom configuration, be sure it has a manifest.yaml."
     fi
 fi)

mkdir -p installer
(cd installer
 installer_bn=$(basename ${INSTALLER})
 if ! [ -f "${installer_bn}" ]; then
     mkdir -p tmp
     cd tmp
     curl -L --remote-name-all ${INSTALLER} ${INSTALLER_CHECKSUM}
     checksums_bn=$(basename ${INSTALLER_CHECKSUM})
     sha256sum -c ${checksums_bn}
     mv ${installer_bn} ${checksums_bn} ..
     cd ..
     rm tmp -rf
 fi
)

mkdir -p cache
mkdir -p builds
mkdir -p tmp
ostree --repo=repo init --mode=archive
ostree --repo=repo-build init --mode=bare-user
