#!/usr/bin/env bash
# This runs after virt-install to undo things leftover from Anaconda.
set -euo pipefail

dn=$(dirname "$0")
# shellcheck source=src/cmdlib.sh
. "${dn}"/cmdlib.sh
# shellcheck source=src/libguestfish.sh
. "${dn}"/libguestfish.sh

src="$1"
shift

set -x
coreos_gf_run "${src}"
# We don't have a way to do this with Anaconda/kickstart right now.
# This bootstraps us to be able to do all of the mounts.
coreos_gf set-label /dev/sda2 boot
coreos_gf_run_mount "${src}"

# Remove some things written by anaconda; eventually
# we want to reset /etc except we also need /etc/fstab right now e.g.
for x in "/etc/sysconfig/anaconda" "/etc/resolv.conf" "/etc/systemd/system/default.target"; do
    coreos_gf rm-rf "${deploydir}${x}"
done
# And blow away all of /var - we want systemd-tmpfiles to be
# canonical
coreos_gf rm-rf "${stateroot}/var/*"

coreos_gf_shutdown
