#!/usr/bin/env bash
# This runs after virt-install to undo things leftover from Anaconda.
set -euo pipefail

dn=$(dirname "$0")
# shellcheck source=src/cmdlib.sh
. "${dn}"/cmdlib.sh
# shellcheck source=src/libguestfish.sh
. "${dn}"/libguestfish.sh

src="$1"
shift

set -x
coreos_gf_run "${src}"
# We don't have a way to do this with Anaconda/kickstart right now.
# This bootstraps us to be able to do all of the mounts.
coreos_gf set-label /dev/sda2 boot
coreos_gf_run_mount "${src}"

fb=/boot/ignition.firstboot
exists=$(coreos_gf exists "${fb}")
if [ "${exists}" = false ]; then
    cat << EOF
---------
  error: Couldn't find ${fb} - most likely Anaconda failed."
  error: If 9pfs is available, you can find logs in: tmp/build/tmp/anaconda"
---------
EOF
    exit 1
fi

# Remove some things written by anaconda; eventually
# we want to reset /etc except we also need /etc/fstab right now e.g.
for x in "/etc/sysconfig/anaconda" "/etc/resolv.conf" "/etc/systemd/system/default.target"; do
    coreos_gf rm-rf "${deploydir}${x}"
done
# And blow away all of /var - we want systemd-tmpfiles to be
# canonical
coreos_gf rm-rf "${stateroot}/var/*"
# And finally, remove cruft from the *physical* root as nothing should be
# using those; Anaconda is creating them today.
for x in $(coreos_gf glob-expand '/*'); do
  case $x in
    /ostree/|/boot/) continue;;
    *) coreos_gf rm-rf "${x}"
  esac
done

coreos_gf_shutdown
