#!/usr/bin/env bash
set -xeuo pipefail

dn=$(dirname $0)
. ${dn}/cmdlib.sh
. ${dn}/libguestfish.sh

# Usage: gf-oemid <input image> <output image> OEMID
# Example: gf-oemid fedora-coreos.qcow2 fedora-coreos-aws.qcow2 ec2
#
# This will add the coreos.oem.id=ec2 to the bootloader arguments. Intended to
# be used for Ignition. It's much faster to do this than generate a fresh image
# for each provider (and also helps ensure the images are otherwise identical).

src=$1
dest=$2
oemid=$3

# We may have a tmpdir injected by an outer build process; if so use it,
# otherwise make our own.
if [ -n "${ASSEMBLER_BUILD_TMPDIR:-}" ]; then
    tmpd=${ASSEMBLER_BUILD_TMPDIR}/gf-oemid
    mkdir ${tmpd}
else
    tmpd=$(mktemp -d /tmp/gf-oemid.XXXXXX)
fi
tmp_dest=${tmpd}/box.img
cp --reflink=auto ${src} ${tmp_dest}
# <walters> I commonly chmod a-w VM images
chmod u+w ${tmp_dest}

coreos_gf_run_mount "${tmp_dest}"
# For now we just modify the grub config, but *not* the /boot/loader
# entry that generated it, because...well it's simpler and in theory
# we only need the OEM ID for the first boot where Ignition runs.  Might
# as well not have other things using it persistently.
grubcfg_src=/boot/grub2/grub.cfg
coreos_gf download ${grubcfg_src} ${tmpd}/grub.cfg
sed -i -e 's,^\(linux16 .*\),\1 coreos.oem.id='${oemid}',' ${tmpd}/grub.cfg
coreos_gf upload ${tmpd}/grub.cfg ${grubcfg_src}
coreos_gf_shutdown

mv "${tmp_dest}" "${dest}"
rm ${tmpd} -rf
