#!/usr/bin/env bash
set -xeuo pipefail

dn=$(dirname $0)
. ${dn}/cmdlib.sh
. ${dn}/libguestfish.sh

# Usage: gf-oemid <input image> <output image> OEMID
# Example: gf-oemid fedora-coreos.qcow2 fedora-coreos-aws.qcow2 ec2
#
# This will add the coreos.oem.id=ec2 to the bootloader arguments. Intended to
# be used for Ignition. It's much faster to do this than generate a fresh image
# for each provider (and also helps ensure the images are otherwise identical).

src=$1
dest=$2
oemid=$3

tmpd=$(mktemp -td gf-oemid.XXXXXX)
tmp_dest=${tmpd}/box.img
cp --reflink=auto ${src} ${tmp_dest}
# <walters> I commonly chmod a-w VM images
chmod u+w ${tmp_dest}

coreos_gf_run_mount "${tmp_dest}"

# Inject OEM label in all relevant places:
# * grub config
# * BLS config (for subsequent config regeneration)
grubcfg_path=/boot/loader/grub.cfg
coreos_gf download ${grubcfg_path} ${tmpd}/grub.cfg
sed -i -e 's,^\(linux16 .*\),\1 coreos.oem.id='${oemid}',' ${tmpd}/grub.cfg
coreos_gf upload ${tmpd}/grub.cfg ${grubcfg_path}
blscfg_path=$(coreos_gf glob-expand /boot/loader/entries/ostree-*.conf)
coreos_gf download ${blscfg_path} ${tmpd}/bls.conf
sed -i -e 's,^\(options .*\),\1 coreos.oem.id='${oemid}',' ${tmpd}/bls.conf
coreos_gf upload ${tmpd}/bls.conf ${blscfg_path}

coreos_gf_shutdown

mv "${tmp_dest}" "${dest}"
rm ${tmpd} -rf
