#!/usr/bin/python3
# This is a completely stupid and incomplete "downgrader"
# from Ignition spec 3 to spec 2.  It is currently only
# used as an implementation detail of the `run` command,
# although part of the idea is to have a shared place
# to maintain this tooling for other purposes, even if
# we aren't yet ready to support it for broader uses
# (such as targeting a spec3 Ignition config at both FCOS and CL, etc.)
import sys
import json
import shutil
import argparse

# Parse args and dispatch
parser = argparse.ArgumentParser()
parser.add_argument("path", help="Ignition file")
args = parser.parse_args()

if args.path == '-':
    f = sys.stdin
else:
    f = open(args.path)
ign = json.load(f)
v = ign['ignition']['version']
vmajor = int(v.split('.', 2)[0])
if vmajor == 2:
    shutil.copyfileobj(sys.stdin, sys.stdout)
    sys.exit(0)
elif vmajor != 3:
    raise SystemExit(f"Unsupported version {v}")
ign['ignition']['version'] = '2.2.0'
for f in ign.get('storage', {}).get('files', []):
    f['filesystem'] = "root"
    append = f.get('append')
    if append is not None:
        f['append'] = True
        if len(append) != 1:
            raise SystemExit(f"Can't handle multiple append: {f['path']}")
        f['contents'] = append[0]

# replace the merge keyword with append
ignconfig = ign['ignition'].get('config', {})
merge = ignconfig.pop('merge', None)
if merge is not None:
    ignconfig['append'] = merge

json.dump(ign, sys.stdout)
