#!/bin/bash
set -euo pipefail

if [ ! -f /etc/cosa-supermin ]; then
    dn=$(dirname "$0")
    # shellcheck source=src/cmdlib.sh
    . "${dn}"/cmdlib.sh

    img_src=$1; shift
    if [[ $img_src == *.gz || $img_src == *.xz ]]; then
        img="$(basename "$img_src")"
        fatal "Cannot pack osmet from $img; not an uncompressed image"
    fi

    workdir=$(pwd)

    device_opts=
    if [[ "${img_src}" == *metal4k* ]]; then
        device_opts=",physical_block_size=4096,logical_block_size=4096"
    fi

    # stamp it with "coreos" serial so we find it easily in the VM
    runvm -drive "if=none,id=coreos,format=raw,readonly=on,file=${img_src}" \
        -device "virtio-blk,serial=coreos,drive=coreos${device_opts}" -- \
        /usr/lib/coreos-assembler/osmet-pack "$@"

    exit 0
fi

# This runs inside supermin

osmet_dest=$1; shift
checksum=$1; shift
speed=$1; shift

set -x

mkdir -p /sysroot
rootfs=/dev/disk/by-id/virtio-coreos-part4
mount -o ro "${rootfs}" /sysroot
osname=$(ls /sysroot/ostree/deploy)
deploydir=$(find "/sysroot/ostree/deploy/$osname/deploy" -mindepth 1 -maxdepth 1 -type d)
# shellcheck disable=SC1090,SC1091
description=$(. "${deploydir}/etc/os-release" && echo "${PRETTY_NAME}")

# we want to use the coreos-installer from the target system but we need to
# chroot into it to avoid linking issues
for mnt in dev proc sys run var tmp; do
    mount --rbind /$mnt "${deploydir}/$mnt"
done

case "$speed" in
    fast)      fast=--fast ;;
    normal)    fast=       ;;
    *)         exit 1      ;;
esac

# We don't want double quotes for `fast`, which may be ''
# shellcheck disable=SC2086
RUST_BACKTRACE=full chroot "${deploydir}" coreos-installer pack osmet \
    /dev/disk/by-id/virtio-coreos \
    --description "${description}" \
    --checksum "${checksum}" \
    --output "${osmet_dest}" $fast
