#!/bin/bash
set -euo pipefail
# Clean up tmpdir when terminated
tpm_dir="$1"
shift
setpriv --pdeathsig SIGTERM swtpm socket \
        --terminate \
        --tpmstate dir="${tpm_dir}" --tpm2 \
        --ctrl type=unixio,path="${tpm_dir}/swtpm-sock" &
trap 'rm -rf ${tpm_dir}' EXIT
wait
