#!/usr/bin/env python3
# NOTE: PYTHONUNBUFFERED is set in cmdlib.sh for unbuffered output
#
# Wrapper for virt-install designed to run in a container
# environment, and using defaults targeted for CoreOS.
# https://github.com/cgwalters/coreos-assembler/issues/7
# Today, this requires a Kickstart (and an installer ISO path);
# we might change things down the line to have defaults for
# one or both.

import os,sys,argparse,subprocess,io,time,re,multiprocessing
import tempfile,shutil,yaml,platform

def fatal(msg):
    print('error: {}'.format(msg), file=sys.stderr)
    raise SystemExit(1)

parser = argparse.ArgumentParser()
parser.add_argument("--dest", help="Destination disk",
                    action='store', required=True)
parser.add_argument("--create-disk", help="Automatically create disk as qcow2, parsing kickstart for size",
                    action='store_true')
parser.add_argument("--image-config", help="coreos-assembler image.yaml",
                    action='store')
parser.add_argument("--variant", help="Use an internal (kickstart) config",
                    choices=('metal', 'metal-uefi', 'cloud'), default=None)
parser.add_argument("--kickstart", help="Kickstart path",
                    action='store')
parser.add_argument("--kickstart-out", help="Save flattened kickstart",
                    action='store')
parser.add_argument("--location", help="Installer location",
                    action='store', required=True)
parser.add_argument("--memory", help="Memory size in MB",
                    action='store', type=int,
                    default=os.environ.get("VIRT_INSTALL_MEMORY", 2048))
parser.add_argument("--console-log-file", help="Console log file",
                    action='store')
parser.add_argument("--logs", help="Copy Anaconda logs to DIR",
                    action='store', metavar="DIR")
# Note https://bugzilla.redhat.com/show_bug.cgi?id=1379389
parser.add_argument("--ostree-repo", help="Path to OSTree repo",
                    action='store', required=True)
parser.add_argument("--ostree-stateroot", help="OSTree stateroot",
                    action='store')
parser.add_argument("--ostree-ref", help="OSTree ref",
                    action='store')
parser.add_argument("--delete-ostree-ref", help="Delete the OSTree ref after installation",
                    action='store_true')
parser.add_argument("--ostree-remote", help="OSTree remote",
                    action='store')
parser.add_argument("--wait", help="Number of minutes to wait",
                    action='store', type=int,
                    default=os.environ.get("VIRT_INSTALL_WAIT", 10))
args = parser.parse_args()

# Copy of bits from https://pagure.io/standard-test-roles/pull-request/223
def get_libvirt_smp_arg():
    """Determine the number of CPUs that should be visible in the guest.
    See e.g. https://www.redhat.com/archives/libvirt-users/2017-June/msg00025.html
    We want to match the number of host physical cores.
    """

    # When running under K8S, the scehduling may be much more restrictive than
    # physical core count, and the code below will assign that count, leading
    # to a VM hang. (e.g. 64 vcpu's to a 1 cpu assignment...)
    p1c = open("/proc/1/cgroup")
    if re.search(r'.*kubepods.*', p1c.read()):
        return '--vcpus=sockets=1,cores=1,threads=1'

    # We may be run in a cgroup with fewer cores available than physical.
    available_cpu = int(subprocess.check_output(['nproc']).strip())
    # https://stackoverflow.com/questions/6481005/how-to-obtain-the-number-of-cpus-cores-in-linux-from-the-command-line
    core_sockets = set()
    for line in io.BytesIO(subprocess.check_output(['lscpu', '-b', '-p=Core,Socket'])):
        if line.startswith(b'#'):
            continue
        core_sockets.add(line.strip())
    sockets = min(available_cpu, len(core_sockets))
    return '--vcpus=sockets={},cores=1,threads=1'.format(sockets)

def run(fn, argv, **kwargs):
    print("cmd: {}".format(subprocess.list2cmdline(argv)))
    return fn(argv, **kwargs)

def run_sync_verbose(argv, **kwargs):
    run(subprocess.check_call, argv, **kwargs)

if args.kickstart_out:
    ks_tmp = open(args.kickstart_out, 'w')
else:
    ks_tmp = tempfile.NamedTemporaryFile(mode='w', prefix="coreos-virtinstall", suffix=".ks")

disk_size = None

if args.variant is not None:
    assert args.kickstart is None
    if args.variant == 'metal-uefi':
        variant_ks = 'metal'
    else:
        variant_ks = args.variant
    with open(f'/usr/lib/coreos-assembler/image-{variant_ks}.ks') as f:
        shutil.copyfileobj(f, ks_tmp)

if args.image_config:
    with open('/usr/lib/coreos-assembler/image-base.ks') as basef:
        shutil.copyfileobj(basef, ks_tmp)
    image_conf = None
    with open(args.image_config) as f:
        image_conf = yaml.safe_load(f)
    disk_size = int(image_conf['size'])
elif args.kickstart:
    run_sync_verbose(['ksflatten', '-c', args.kickstart], stdout=ks_tmp)
else:
    raise SystemExit("Either --kickstart or --image-conf must be specified")

# This is an implementation detail of https://github.com/coreos/ignition-dracut
# So we hardcode it here.
# See: https://github.com/coreos/ignition-dracut/pull/12
ks_tmp.write("""
%post --erroronfail
touch /boot/ignition.firstboot
%end
""")

# Grab the ipv4 address of the container
default_iface = subprocess.check_output(['ip', '-4', 'route', 'list', '0/0']).split()[4]
output = subprocess.check_output(['ip', '-4', '-oneline', 'addr', 'show', default_iface])
ipv4 = re.match('.*inet ([\d.]+)/\d\d.*', str(output)).group(1)

if args.ostree_repo:
    assert args.ostree_stateroot
    assert args.ostree_remote
    assert args.ostree_ref
    ks_tmp.write(f"""
ostreesetup --nogpg --osname={args.ostree_stateroot} --remote={args.ostree_remote} --url=http://{ipv4}:8000/ --ref="{args.ostree_ref}"
    """)
# Hacky bits to copy out all of the Anaconda logs on shutdown
if args.logs:
    ks_tmp.write("""
%pre
set -euo pipefail
mkdir -p /mnt/logs
mount -t 9p -o rw,trans=virtio,version=9p2000.L /mnt/logs /mnt/logs
cat >/etc/systemd/system/coreos-virtinstall-logs.service <<EOF
[Unit]
RequiresMountsFor=/mnt/logs
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStop=/bin/sh -c 'cp /tmp/*.log /mnt/logs'
EOF
systemctl daemon-reload
systemctl start coreos-virtinstall-logs
%end
    """)

# Support using commits only
if args.delete_ostree_ref:
    print("virt-install: Will remove ostree ref")
    ks_tmp.write(f"""
%post --erroronfail
ostree refs --delete {args.ostree_remote}:{args.ostree_ref}
%end
""")

# This is an "extension" to kickstart files that we implement as a comment.
if args.create_disk and args.kickstart:
    magic_virt_install_size_str = '#--coreos-virt-install-disk-size-gb:'
    disk_re = re.compile(r'^' + magic_virt_install_size_str + ' *([0-9]+)$')
    with open(args.kickstart) as f:
        for line in f:
            m = disk_re.search(line)
            if not m:
                continue
            disk_size = int(m.group(1))
            break
    if disk_size is None:
        fatal("--create-disk specified, but failed to find '{}' in kickstart".format(magic_virt_install_size_str))

if args.create_disk:
    if args.variant in ('metal', 'metal-uefi'):
        fmt = 'raw'
    else:
        fmt = 'qcow2'
    run_sync_verbose(['qemu-img', 'create', '-f', fmt, args.dest, '{}G'.format(disk_size)])
    print("Created initial disk: {} with size {}G".format(args.dest, disk_size))

# Now a hack to avoid libvirt race conditions; it's
# activated by the cmdline (and exits after 30s), and in virt-install the daemon
# might not have grabbed the socket by the time the rest of the virt-install
# code tries to talk to it.
# https://github.com/coreos/coreos-assembler/issues/31
# At some point we'll talk to qemu directly.
for x in range(10):
    if subprocess.call(['virsh', '--connect=qemu:///session', 'version'], stdout=subprocess.DEVNULL) == 0:
        break
    print("Waiting for libvirt {}/10", x)
    time.sleep(1)

# Doesn't need to be truly unique, let's just use our pid+time
domain="coreos-inst-{}-{}".format(os.getpid(),int(time.time()))
tail_proc = None
http_proc = None

# See the use of this below; also note virt-install also output the version to
# stderr and not stdout.
have_virtinstall_2 = int(subprocess.check_output(['virt-install', '--version'],
                                                 stderr=subprocess.STDOUT).strip().decode('UTF-8').split('.')[0]) >= 2

ks_tmp.flush()

try:
    vinstall_args = ["virt-install", "--connect=qemu:///session",
                     "--name={}".format(domain)]
    # use noautoconsole for fedora since we will use console=log.file
    # for el7 just use the serial console
    if os.environ['ISFEDORA'] != '':
        vinstall_args.append('--noautoconsole')
    else:
        vinstall_args.append('--nographics')
    if args.console_log_file:
        vinstall_args.append("--console=log.file={}".format(args.console_log_file))
        tail_proc = subprocess.Popen(['tail', '-F', args.console_log_file])
    # Start webserver to serve the ostree content to be retrieved during install
    # Sadly this logs to stderr by default, so let's silence it.  Also this is currently
    # racy, we need to at some point poll for the webserver to be up.
    http_proc = subprocess.Popen(['python3', '-m', 'http.server', '--bind', ipv4, '8000'], cwd=args.ostree_repo,
                                 stderr=subprocess.DEVNULL)
    if args.logs:
        vinstall_args.append("--filesystem=source={},target=/mnt/logs,accessmode=mapped".format(args.logs))
    location_arg = f"--location={args.location}"
    if have_virtinstall_2:
        # This way we don't go through libosinfo.  This is hardcoding the layout of the
        # ISO, but that's fine since we pin a version of it.
        # https://bugzilla.redhat.com/show_bug.cgi?id=1659242

        # set correct location of the kernel image and initrd
        arch = platform.machine()
        if arch == "x86_64" or arch == "i386":
            location_arg += ",kernel=isolinux/vmlinuz,initrd=isolinux/initrd.img"
        elif arch == "ppc64le":
            location_arg += ",kernel=ppc/ppc64/vmlinuz,initrd=ppc/ppc64/initrd.img"
        elif arch == "aarch64":
            location_arg += ",kernel=images/pxeboot/vmlinuz,initrd=images/pxeboot/initrd.img"
        elif arch == "s390x":
            location_arg += ",kernel=images/kernel.img,initrd=images/initrd.img"
        else:
            raise SystemExit("Unknown machine architecture "+arch+" can't determine the kernel and initrd location")

    vinstall_args.extend(["--wait={}".format(args.wait), "--noreboot", "--nographics",
                          "--memory={}".format(args.memory), get_libvirt_smp_arg(),
                          "--os-variant=rhel7.6", "--rng=/dev/urandom",
                          "--cpu=host-passthrough",
                          "--check", "path_in_use=off",
                          "--network=user",  # user mode networking
                          location_arg,
                          "--disk=path={},cache=unsafe".format(args.dest),
                          "--initrd-inject={}".format(ks_tmp.name),
                          "--extra-args", "ks=file://{} console=tty0 console=ttyS0,115200n8 inst.cmdline inst.notmux".format(os.path.basename(ks_tmp.name))])
    if args.variant == 'metal-uefi':
        vinstall_args.append('--boot=uefi')
    run_sync_verbose(vinstall_args)
    # And strip out all of the Anaconda stuff in /var; this uses libguestfs
    # to ensure we fully control the code.
    cleanup_argv = ['/usr/lib/coreos-assembler/gf-anaconda-cleanup', args.dest]
    if args.image_config is None:
        cleanup_argv.append('--skip-partition-fixups')
    run_sync_verbose(cleanup_argv)
finally:
    subprocess.call(['virsh', '--connect=qemu:///session', 'undefine', domain])
    if tail_proc is not None:
        tail_proc.terminate()
    if http_proc is not None:
        http_proc.terminate()
print("Completed install to disk image: {}".format(args.dest))
