FROM registry.redhat.io/rhel10/nginx-126:10.1

ADD nginx.conf "${NGINX_CONF_PATH}"

COPY index.html /usr/share/nginx/html/index.html

# TLS material
USER 0
COPY tls/ /etc/nginx/tls/
RUN chown -R 1001:0 /etc/nginx/tls
USER 1001

CMD ["nginx", "-g", "daemon off;"]
